### ISSUE TITLE
[Feature Request] Save Settings to File

### ISSUE THREAD

**Issue by oak83** [threethan/LightningLauncher#10]
Hello! 
Thanks a lot for your launcher! 
It's the most convenient of all that I have tried on the Oculus! 
Tell me, please, do you plan to make the function of saving settings (list of groups, sorting of apps) in a user folder or in android\data?

**Comment by ConSolatory** [comment]
Re-application - there is no way to save the screen after zooming.
The launch of the application always occurs with only two rows.
If the application is expanded to a larger size - then after closing or any click - the application resets the default size settings to two rows. It's very inconvenient - when it's so narrow.

**Comment by threethan** [comment]
> Re-application - there is no way to save the screen after zooming. The launch of the application always occurs with only two rows. If the application is expanded to a larger size - then after closing or any click - the application resets the default size settings to two rows. It's very inconvenient - when it's so narrow.

**Comment by threethan** [comment]
I currently have no plans to implement this, but it is a fine idea and I will happily accept a PR with this functionality.

**Comment by threethan** [comment]
Added as of 6.0.0
