### ISSUE TITLE
Instalation of Lightning Launcher Failed to download package

### ISSUE THREAD

**Issue by PaulRacey** [threethan/LightningLauncher#101]
As the title states I get the following error when downloading lightning launcher:

Failed to download package!
Please check your internet connection and try again later.

Only thing is, my internet is fine and even when hard wiring the headset onto my pc didn't work.

I am using quest 2, and downloading through the SIDEQUEST headset app.

**Comment by threethan** [comment]
Resolved, more info on https://github.com/threethan/LightningLauncher/issues/102
