### ISSUE TITLE
Crash shortly after starting the launcher

### ISSUE THREAD

**Issue by johnny2trayz** [threethan/LightningLauncher#104]
It just keeps crashing.  It's also listed as using 4 gigs of wifi data.

**Comment by sterankin** [comment]
Having this issue also which just started today. The launcher crashes after a few seconds, even if you open it and do not use it - it will crash.

**Comment by Cesarus85** [comment]
Also having this crashes after a few seconds.
Is it normal that when I resize a opened Android App the App becomes a black filled space?
When I launch outside Lightning Launcher resizing the App window works…

**Comment by fox1047** [comment]
Same for me. I tried clearing cache and storage and removing horizon shortcut, but issue persists.

**Comment by PiniponSelvagem** [comment]
It was crashing for me too, but a new update on SideQuest fixed it, version 7.0.1 I believe.

**Comment by Cesarus85** [comment]
Can confirm, updating with Sidequest solves the problem

**Comment by johnny2trayz** [comment]
Same. The groups get all messed up but if you hit reset to default everything works. Except the Monday.com thing is puzzling to me. I even installed the actual app and still does nothing.

**Comment by sterankin** [comment]
Looks like this may have been caused by the release of 7.0.1 yesterday.  I'm not sure if the app is trying to download the update but something about that check is causing a crash.

Sideloading 7.0.1 fixed it.

**Comment by threethan** [comment]
Can anyone replicate this issue on 7.0.1?

If you are on 7.0.0, you may need to perform a manual update - either by downloading from GitHub, or using side quest.

**Comment by threethan** [comment]
If you have any issues other than "Crashes" - please create a new issue, don't just leave a comment on a different one.

**Comment by threethan** [comment]
7.0.1 fixes a number of potential crashes relating to unexpected null values, which should most likely resolve this issue.
