### ISSUE TITLE
Friends in discord can't hear me while in game

### ISSUE THREAD

**Issue by CrusaderStar1993** [threethan/LightningLauncher#105]
So I can hear them just fine while in a game. But they are completely unable to hear me.

**Comment by threethan** [comment]
Are you using [Lightning Browser](https://github.com/threethan/LightningBrowser)? If so, create an issue on that repository. Keep in mind that Android only allows one application to use the mic at time. So, if the game you're playing uses the mic for voice chat, Lightning Browser will be unable to access it

**Comment by CrusaderStar1993** [comment]
> Are you using [Lightning Browser](https://github.com/threethan/LightningBrowser)? If so, create an issue on that repository. Keep in mind that Android only allows one application to use the mic at time. So, if the game you're playing uses the mic for voice chat, Lightning Browser will be unable to access it. I think disabling mic access in the game i was playing fixed it. Thank you
