### ISSUE TITLE
Missing some apps

### ISSUE THREAD

**Issue by FranciscoMurias** [threethan/LightningLauncher#106]
Hey, just wanted to highlight an issue I'm having with the launcher, it appears some apps are missing entirely such as:

xbox cloud app
meta move app
meta feed app
meta store
messenger

not sure if there's any way to force these to show up or if this is a known issue, any help is welcome.
thanks for making this

**Comment by DevanWolf** [comment]
Don't forget systemux://file-viewer

**Comment by threethan** [comment]
Resolved the missing apps, and added the ability to open PWAs (such as the xbox cloud app), in 7.0.2!

systemux://file-viewer does not exist, but systemux://file-manager can still be opened.

**Comment by DevanWolf** [comment]
> Resolved the missing apps, and added the ability to open PWAs (such as the xbox cloud app), in 7.0.2!
> 
> systemux://file-viewer does not exist, but systemux://file-manager can still be opened.

But is there a correct systemux path for File Viewer? I know It can't be seen in the apps list but can only be found by opening an image or video file using Quest File Manager or Camera and can be pinned to universal menu normally for quick access.

**Comment by threethan** [comment]
The "file viewer" can be opened with `systemux://media_preview`. However, I don't see any use case for opening it directly. Doing so gives you a mostly-blank screen with a link to the camera app. While it can be added to the dock, the file viewer does not appear as an application in Meta's App Library; its clear it's not particularly meant to be launched externally. 

I'm going to opt to keep it out of the launcher for the same reason as the air link app is kept out of the launcher: There are better ways to access it, and launching it directly may not do what a user expects.
