### ISSUE TITLE
App Shortcuts not working on the Simplified Chinese Version  of Oculus

### ISSUE THREAD

**Issue by YrracOwl** [threethan/LightningLauncher#108]
## Phenomenon
I followed the guidings of Lightning Launcher to create the shortcuts, but those shortcuts constantly showed in **unkown source**，any hover gesture or click "messenger" can trigger the Lightning Launcher

**Comment by threethan** [comment]
The shortcuts do show up in "unknown sources," this is expected. Each shortcut works independently, only on the app or icon indicated.

You said that you _can_ trigger Lightning Launcher with hover or click. This seems to be correct. Is it triggering when not expected? Is there text which indicates it should work in a different way?

I think that something may be lost in translation. It might help if you could send pictures or video of your issue.

**Comment by YrracOwl** [comment]
> The shortcuts do show up in "unknown sources," this is expected. Each shortcut works independently, only on the app or icon indicated.
> 
> You said that you _can_ trigger Lightning Launcher with hover or click. This seems to be correct. Is it triggering when not expected? Is there text which indicates it should work in a different way?
> 
> I think that something may be lost in translation. It might help if you could send pictures or video of your issue.

sry for the sentence " can trigger"，actually it should be " can't trigger"...

I install all the shortcuts except "app Library", the horizon feed and the people can work through the "hover" action. "Messenger" not work, and "Monday.com" is missing.

But the horizon feed and the people works fine. I think it's enough. 

Thx anyway. Maybe the translation mismatch causes the problem.

**Comment by threethan** [comment]
Can you get the official "Monday.com" in the Meta Quest Store? It may not appear because the official version is not available in your region.

What happens when you click on the "Messenger" icon?

Messenger and Monday.com work on click. Other shortcuts work on hover.

**Comment by threethan** [comment]
I am going to close this issue as I cannot resolve it without more information. If anyone can identify specific issues with the translation, feel free to create a new issue or pull request. I will reopen the issue if I receive more specific information.
