### ISSUE TITLE
close app button missing

### ISSUE THREAD

**Issue by keld107** [threethan/LightningLauncher#110]
there used to be a close app button avilable on each app from the launcher next to the 3 dots menu that would be visible if sound was playing from an app/ website. that is no longer there.

**Comment by threethan** [comment]
This was changed in version 7. The 'stop' button for websites no longer appears on the launcher and is now part of LightningBrowser. To stop an added website from running in the background, open it normally, and then press the 'stop' button in the browser's toolbar.

This button was never available for native apps.
