### ISSUE TITLE
Crash while attempted to automatically install Lightning Browser

### ISSUE THREAD

**Issue by darkimage404** [threethan/LightningLauncher#113]
LightingBrowser dialog to install it fail download in QUEST3

(what is the correct version for quest3?)

"Main build is armeabi-v7a only. Arm64 build is arm64-v8a only. If installing through Lightning Launcher, the correct build will be selected automatically."

**Comment by threethan** [comment]
Fixed by 5eb2d8c3b51ce6798ef1c7835dfa9b97b7a210df

**Comment by darkimage404** [comment]
@threethan 
still doesn't automatically install the browser, tries to do something but then crashes.
Permissions are all active (including the one to install applications from unknown sources)

I still installed "LightningBrowser_Arm64.apk", hopefully the correct version for Quest3

**Comment by threethan** [comment]
New issue resolved by https://github.com/threethan/LightningLauncher/commit/93b71f027512c7ac0808be66c2b32990d2f43147
