### ISSUE TITLE
Crash on attempted installation of remote packages

### ISSUE THREAD

**Issue by taminator69** [threethan/LightningLauncher#114]
I've tried every shortcut installation and every time I try to install it.
The launcher closes/crashes.

I've done 2 reinstalls, it's not a huge issue, but I would like to not have to click open the app menu to load the launcher.
Would being in the PTC affect this?

**Comment by HoneyBajjar** [comment]
The same thing is happening to me, I cannot seem to install any of the shortcuts. The app just crashes as soon as I hit "install"

**Comment by ddark008** [comment]
The same problems on the latest v60 firmware

**Comment by threethan** [comment]
Resolved by https://github.com/threethan/LightningLauncher/commit/93b71f027512c7ac0808be66c2b32990d2f43147
