### ISSUE TITLE
don't update itselft 7.1.0 -> 7.1.1

### ISSUE THREAD

**Issue by darkimage404** [threethan/LightningLauncher#115]
I love this project, I use it a lot to use discord in the background, so I hope my reports are appreciated.

This happens:
the update popup appears, I accept the update, I wait, nothing happens and the application closes after a few seconds.

**Comment by threethan** [comment]
This issue is resolved on 7.1.1. Please install the update manually or through sidequest. Very sorry for the inconvenience.
