### ISSUE TITLE
Crash on Update or Package Download

### ISSUE THREAD

**Issue by IndyGibb** [threethan/LightningLauncher#117]
Whenever I try to update it, or create a shortcut, it crashes. I like how it looks and I think it would be very nice to be able to use this launcher, but since it crashes so much currently it is not worth it. I have tried reinstalling it through sidequest and that neither updates it nor fixes the crashes.

**Comment by ShoderPL** [comment]
Quest 3, same problem

**Comment by threethan** [comment]
This issue is resolved on 7.1.1. Please install the update manually or through sidequest. Very sorry for the inconvenience.
