### ISSUE TITLE
Library shortcut service does not work

### ISSUE THREAD

**Issue by ShoderPL** [threethan/LightningLauncher#119]
Lightning Launcher 7.1.1 on Quest 3, shortcuts still not working :/

**Comment by threethan** [comment]
Please provide more information on your issue.

**Comment by ShoderPL** [comment]
In earlier versions, when I set a shortcut to the app library, clicking on it would launch Lightning Launcher. Currently, when I set the shortcut and click on the app library, nothing happens; it just opens the standard library.

**Comment by Cophe** [comment]
me too it just opens the standard library.

**Comment by threethan** [comment]
Do you experience the same or a similar issue with any of the other shortcut services?

**Comment by Cophe** [comment]
I'll try it out after work. Thanks for the effort, devs.

**Comment by giannim24** [comment]
I'm on the latest firmware for the Quest 3 and I am also having issues with shortcuts. The Monday.com and Facebook shortcuts do not work however I was able to get one of the hover ones working, forgot which one. The Facebook and Monday.com shortcuts get installed and are on the list under unknown sources but I can't seem to turn it into an icon on the bar. Am I doing something wrong?

**Comment by underoll** [comment]
Just a guess. Your interface language might be not English.

The shortcut service workability depends on an icon label, and it's expected to be 'Library' or 'App Library'.
https://github.com/threethan/LightningLauncher/blob/e80a9736a19153c7e55b336a0e1ce2f987ca81b6/AppLibraryShortcutService/app/src/main/java/com/threethan/launcher/service/library/ShortcutAccessibilityService.java#L14

**Comment by giannim24** [comment]
> Just a guess. Your interface language might be not English.
> 
> The shortcut service workability depends on an icon label, and it's expected to be 'Library' or 'App Library'.
> 
> https://github.com/threethan/LightningLauncher/blob/e80a9736a19153c7e55b336a0e1ce2f987ca81b6/AppLibraryShortcutService/app/src/main/java/com/threethan/launcher/service/library/ShortcutAccessibilityService.java#L14

My language is English.

**Comment by Synaps33** [comment]
I must compile app to use Polish, or there is easier way?

**Comment by threethan** [comment]
These shortcuts rely on language-specific strings. Strings are includes in localization files for every language which is supported on the Quest. That means the shortcuts are NOT language-dependent, but may need to be updated if Meta changes the translations.

These shortcuts open on _hover,_ not on click. This is explained if you read their descriptions.

As to why this is not working, either:
- Meta has changed the names of some apps, so I'll need to update the strings accordingly (which has been happening a lot lately)
- Some system functionality has changed so that the shortcut services no longer work
- People are failing to actually "activate" the accessibility services as instructed

I will resolve this if and when I am able to replicate the issue on my device, or if I receive enough information to identify the actual issue.

**Comment by underoll** [comment]
Oh, I haven't find localization files.

The localization is wrong at least for Russian now. It must be just "Библиотека" not "Библиотека приложений".
Meta Quest 3 v62

The Library shortcut works great for me when I switch to English.

**Comment by antomanc** [comment]
I can confirm that with the language set to English(US), the library shortcut works perfectly, but when I switch to my language, Italian, the library shortcut stops working.

**Comment by underoll** [comment]
If it will help, here are localization strings extracted from Quest firmware (SystemUX.apk)
```
./resources/res/values-el/strings.xml:    <string name="library_display_name_side_nav_enabled">Βιβλιοθήκη</string>
./resources/res/values-nl/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliotheek</string>
./resources/res/values-zh-rTW/strings.xml:    <string name="library_display_name_side_nav_enabled">資料庫</string>
./resources/res/values-fr/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliothèque</string>
./resources/res/values-fi/strings.xml:    <string name="library_display_name_side_nav_enabled">Kirjasto</string>
./resources/res/values-ja/strings.xml:    <string name="library_display_name_side_nav_enabled">ライブラリ</string>
./resources/res/values-de/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliothek</string>
./resources/res/values-pt-rPT/strings.xml:    <string name="library_display_name_side_nav_enabled">Biblioteca</string>
./resources/res/values-tr/strings.xml:    <string name="library_display_name_side_nav_enabled">Kütüphane</string>
./resources/res/values-nb/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliotek</string>
./resources/res/values-ro/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliotecă</string>
./resources/res/values-es/strings.xml:    <string name="library_display_name_side_nav_enabled">Biblioteca</string>
./resources/res/values-zh-rCN/strings.xml:    <string name="library_display_name_side_nav_enabled">资源库</string>
./resources/res/values-pt/strings.xml:    <string name="library_display_name_side_nav_enabled">Biblioteca</string>
./resources/res/values-da/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliotek</string>
./resources/res/values-zh-rHK/strings.xml:    <string name="library_display_name_side_nav_enabled">資料庫</string>
./resources/res/values-pl/strings.xml:    <string name="library_display_name_side_nav_enabled">Biblioteka</string>
./resources/res/values-sv/strings.xml:    <string name="library_display_name_side_nav_enabled">Bibliotek</string>
./resources/res/values-it/strings.xml:    <string name="library_display_name_side_nav_enabled">Libreria</string>
./resources/res/values/strings.xml:    <string name="library_display_name_side_nav_enabled">Library</string>
./resources/res/values/public.xml:    <public type="string" name="library_display_name_side_nav_enabled" id="2131690417" />
./resources/res/values-ko/strings.xml:    <string name="library_display_name_side_nav_enabled">라이브러리</string>
./resources/res/values-es-rES/strings.xml:    <string name="library_display_name_side_nav_enabled">Biblioteca</string>
./resources/res/values-ru/strings.xml:    <string name="library_display_name_side_nav_enabled">Библиотека</string>
./resources/res/values-fb/strings.xml:    <string name="library_display_name_side_nav_enabled">[Library#67a1fb25303bd7cbb89a8f5067a0945d:1]</string>
./resources/res/values-cs/strings.xml:    <string name="library_display_name_side_nav_enabled">Knihovna</string>
```

**Comment by mikudream** [comment]
In Simplified Chinese, the name of the Library has been changed from "资源库" to "应用库". After updating the corresponding name locally, it can now function normally

**Comment by Mayki07** [comment]
I have the same problem, if I leave Quest in my Czech language it opens the standard library, if I switch the language to English it opens the launcher instead of the library. Would it be possible to solve this somehow?

**Comment by threethan** [comment]
I've created a script to extract strings for all shortcut services. Should roll out with the next update.
