### ISSUE TITLE
Open in app window

### ISSUE THREAD

**Issue by bennodxb** [threethan/LightningLauncher#129]
V63 Quest firmware now shows sideloaded apps in the taskbar which is fantastic!
But, If I launch in anything other than default window they show up as "lightning launcher" instead of the actual app name and cannot be launched from that taskbar shortcut. It would be great to be able to keep using the launch options in lightning but benefit from teh great v63 update.
Thanks

**Comment by threethan** [comment]
You can long-press any app and select "Open in Own Window." You may also wish to enable "Open Apps in Own Window by Default" under advanced settings.

**Comment by bennodxb** [comment]
Thanks mate. 

Yeah i know that. It doesn't do what I'm suggesting though.

Open in own window opens the apps in phone size portrait mode. 

Large wide is the best but it doesn't take advantage of the new update. 

It's your app, do as you want but the change is probably the best thing that could have happened to lightning launcher if it could take advantage of it properly. I'm amazed that they even allowed it to happen so not taking advantage of it seems very unfortunate.

**Comment by threethan** [comment]
These custom window sizes only work by opening the target app in a new Lightning Launcher window. The Quest OS is actually correct to report these as instances of LL. The window size is set per-activity in the applications' manifest. The only way to change this would be to fully rebuild the target app, which is well out of scope.

It's still possible to multitask these windows slightly by opening Lightning Launcher from different sources, but I'm afraid that's the best that's currently viable. The quest does, at least, let you resize the phone-style windows when using the further distance from the "Switch Distance" button.
