### ISSUE TITLE
Some banners are "flickering" and cannot be activated with trigger

### ISSUE THREAD

**Issue by s1nn3r** [threethan/LightningLauncher#133]
Hi,
I really love LightningLauncher to get my games organized.
With the latest update I have a strange phenomenon.
Some banners flicker (resizing small/large with a high frequency) when pointing at them. They can hardly be started with the trigger then. Pressing A does start the games though.
I get this on both of my Quest 3s.
A reboot sometimes fixes this for some games, but then other games show this.
Any idea?
Thanks!
s1nn3r

**Comment by threethan** [comment]
It's a bit hard to narrow down, given that I have zero Quest 3s.

Could you add some more info so I can attempt to replicate this issue?
- When you mention the "latest update," do you mean an update to Lightning Launcher, or to the Quest OS?
- Is there any pattern to which banner do or do not have this issue?
- If you use only one controller on the quest, does the issue persist?

If anyone else has this issue, please let me know.

**Comment by s1nn3r** [comment]
Hi threethan,
I meant the update for Lightning Launcher, 7.1.1 didn't show this, but 7.2.0 and 7.2.1 do.
I mostly have games from "unknown sources" installed. All show the correct banner image. Some always "flicker", some stop or start flickering after a Quest reboot. It's like moving the pointer of the controller on the banner and then moving it away and then back, as this resizes the banner, just very fast. But in fact the pointer always stays on the banner.
I am away for 2 days but can test with one controller on the weekend, but I sometimes only use one controller and think it's exactly the same.
I do wonder however that I seem to be the only one experiencing this (with both Quest 3s running even on different meta accounts).

**Comment by Incog5** [comment]
Same issue here, it only effects sideloaded MR (mixed reality) apps. Also a bit odd it's inconsistent sometimes reboot fixes it and sometimes not. A temp solution which has worked is clicking on the three dots options for the specific app with issues and refresh reload the icon thumbnail.

**Comment by threethan** [comment]
Fixed and slated for the next update
