### ISSUE TITLE
[Feature Request] Add a "normal" custom window size

### ISSUE THREAD

**Issue by LivingBuzzard55** [threethan/LightningLauncher#137]
The main problem of windows as they are right now is that when I open an app on default setting I cannot reopen Lightning launcher via the shortcut unless I close the app altogether, also I can’t use two apps configured on default because if I try to open one it will close the other. I would love to be able to look through discord while listnening to some music on Apple Music. Also I noticed I’m not able to use the multiple apps that are configured the same size, please make it possible so that I we can be able to use multiple apps at once.

**Comment by threethan** [comment]
Set apps to "Open in Own Window". These windows are per-app and independent. (As of 7.2, this is the default behaviour.)

The suggestion has already been made to allow multiple applications to use the same custom size, and was rejected due to system limitations.

**Comment by LivingBuzzard55** [comment]
What I meant here is that basically some apps like discord, TikTok Apple Music open in phone aspect ratio by default when on open in own window and when I set the setting to Default window, it opens the app via lightning launcher and it doesn’t allow me to return to lightning launcher unless I close the app altogether and reopen. This doesn’t happen in the large 16:9 setting small 4:3 setting or huge 16:9 setting since it opens another window and allows me to return to lightning launcher normally, my request is to basically open these apps on default setting in a new window so that I can use lightning launcher normally. As to the open multiple apps on the same size I understand what you mean and it’s ok.

**Comment by threethan** [comment]
It seems like the request is to add an additional "custom window" activity which has the same size as the default launcher window. 
I don't think this should be the default behavior, as it differs substantially from the Quest's launcher, but I will target this for the next feature update.
