### ISSUE TITLE
[Feature Request] Ability to create web apps which do not show the URL bar

### ISSUE THREAD

**Issue by LivingBuzzard55** [threethan/LightningLauncher#138]
Basically an option to make the web app look just like an app just like WhatsApp for meta quest, Facebook and Instagram

**Comment by threethan** [comment]
Enable edit mode, then press "add a website" on the bottom-right.

**Comment by LivingBuzzard55** [comment]
I don’t believe you understand the request, what I meant by this is to make an option for web apps to open and basically look like apps or an option to hide the search bar and website controls on web apps by default

**Comment by threethan** [comment]
This is now the default behavior in LightningBrowser 1.2.0.
