### ISSUE TITLE
Can't create a shortcut

### ISSUE THREAD

**Issue by StrangeCorvus** [threethan/LightningLauncher#141]
I have a Quest 2, while I absolutely love this launcher, I hardly ever find myself using it for one simple reason, thanks to recent updates it's been getting harder and harder to navigate through the unknown sources tab.

A few months back all you had to do was search the name of the app and boom. But now Meta made it so that you can only search apps native apps and apps from the store. Typing the name of an unknown source app will give you no results, so the only way is to manually scroll down your list, and personally, mine is quite big.

My issue is that you gotta scroll down all the way down to the letter L.
Personally I wish the app did like other launchers, and had a special character before the name, like a period or a comma. Because that shoots the app all the way up making it the first thing that shows up when you open the unknown sources. 

All that aside. I see that the page has this recommendation, it says to head to "Settings -> Shortcut Settings" to create a Lightening Launcher shortcut. I do not have that feature. I cannot pin LL on my task bar, I can't have it on my app library or shortcuts, nothing.

The only way to access it is through unknown sources. Which is very frustrating.

**Comment by threethan** [comment]
The shortcut settings are in the settings for lightning launcher, which may be accessed using the "cog" button on the top right of the launcher. If you have not yet opened shortcut settings, you will see a white, highlighted button which says "Set Up Shortcuts."

If you are on v65, lightning launcher should show up as an icon in the recents section of the dock once it has been open.

Please let me know which part of this was not clear.
