### ISSUE TITLE
Apps often load in launcher window, not fullscreen

### ISSUE THREAD

**Issue by Mateus109** [threethan/LightningLauncher#143]
Per title, often games/apps often load **within** the Lightning Launcher window, not fullscreen. These are not pirated apps but regular Meta Store purchases.

**Comment by threethan** [comment]
Is your headset's software up to date? (v66 or newer)
Lightning Launcher previously included a workaround for that issue, but the workaround was removed in 7.2.2 as it was seemingly resolved by a software update.

Are there any specific apps or games in which this issue commonly occurs?

**Comment by Mateus109** [comment]
> Is your headset's software up to date? (v66 or newer) Lightning Launcher previously included a workaround for that issue, but the workaround was removed in 7.2.2 as it was seemingly resolved by a software update.
> 
> Are there any specific apps or games in which this issue commonly occurs?

Updating to Quest OS v66 fixed the problem. Thanks
