### ISSUE TITLE
Can you tell me where the code is to open it in a new window?

### ISSUE THREAD

**Issue by cgapk123** [threethan/LightningLauncher#146]
Can you tell me where the code is to open it in a new window?

I need to view the system settings. Use the code that opens in a new window.

**Comment by threethan** [comment]
You can open the android or Quest settings from Lightning Launcher. Code directly related to app launching is in Launch.java.

**Comment by cgapk123** [comment]
I'm very sorry, but I still don't understand how to open the system settings using a new window. This is how my previous code opens the system settings, but it only opens in the original program page, not in a new phone window using the Quest device.

local intentSettings = Intent()
intentSettings.setPackage("com.android.settings")
intentSettings.addCategory(Intent.CATEGORY_LAUNCHER)
activity.startActivity(intentSettings)
activity.finish()
