### ISSUE TITLE
[Feature Request] 21:9 Aspect ratio for custom window size

### ISSUE THREAD

**Issue by Meitoncz** [threethan/LightningLauncher#147]
Hi,

The title says it all - would you be possible to add a option to choose a 21:9 custom sized window same as it is for 16:9 now?
Many thanks.

**Comment by threethan** [comment]
Is there currently any reason to use 21:9 specifically? As of v67, windows can be resized freely in most cases, so if you only want a wide window, that can be done without needing the custom size options.

**Comment by Meitoncz** [comment]
> Is there currently any reason to use 21:9 specifically? As of v67, windows can be resized freely in most cases, so if you only want a wide window, that can be done without needing the custom size options.

My personal reason is I'm using 21:9 resolution when gaming via GeForce Now as it feels more natural to me in a headset and GeForce Now APK doesn't like when sou resize it during a session (sometimes it crashes or behaves weird and stretching the streamed content). It would be really nice to have the option to run it directly in 21:9.

Another solution would be to implement something like "use custom aspect ratio for window" where you would type the aspect ratio yourself if you as a dev don't want to add another specific one.

Thanks 🙏

**Comment by threethan** [comment]
I'll consider it for the next update. Unfortunately, it's not possible to set window sizes programmatically (at least as far as I'm aware). They each need to be manually added as different activities to the manifest, which can't be changed in runtime.
