### ISSUE TITLE
Resolution for game/app thumbnails.

### ISSUE THREAD

**Issue by MakerManu** [threethan/LightningLauncher#149]
Sorry for the question, if I wanted to manually set a cover on the app thumbnails what resolution should I find the image? And what format should it be? Thank.

**Comment by threethan** [comment]
For best results, use 512x512 or greater image for icons, and 512x910 or greater for banners. Icons are 1:1, while banners are 16:9. 

Too-large images are resized, so don't worry too much about resolution.
