### ISSUE TITLE
Missing 'Masters of Light' on Quest 3 in Lightning Launcher

### ISSUE THREAD

**Issue by jmaha** [threethan/LightningLauncher#154]
I noticed the app 'Masters of Light' doesn't appear in Lightning Launcher for some reason. This is the only app I've noticed so far that shows up in the standard Quest Applications panel but doesn't seem to be detected by Lightning Launcher.

**Comment by Celine-COVEN** [comment]
Adding to this: I'm the Game creator of "Masters of Light" - not sure how to resolve this but if LightningLauncher team can give us advice on what to check / modify to make our game visible, it'd be great! The game is easily findable in Quest Store and SideQuest, let us know what to do to fix this!

**Comment by threethan** [comment]
According to [oculusdb](https://oculusdb.rui2015.me/), the game's internal name seems to be "com.Albyon.FightBackPremiumPreAlpha." Lightning Launcher uses the name from the apps' manifest, while the built-in launcher uses the name from it's store page. 

It's possible this app still identifies as some variant of "Fight Back" in it's manifest; see if you can find it with that name. (If so, let me know so I can change the issue title accordingly)

Additionally, Quest app icons & banners are currently 6 months out of date, so the launcher fails to find them for newer apps such as this.

I am hoping to resolve both of these issues in the next update.

**Comment by Celine-COVEN** [comment]
We wont be able to change the game's internal name now it's published on the store (it was our temp name when in development - Fight Back Premium) - it would be great if Lightning Launcher was using the name from the store page. Final names are often chosen late in the process, in QA even. @jmaha  I hope you can find it with "Fight Back" or "FightBackPremiumPreAlpha". 
The app was published in May 16th, so indeed less than 6 months!

**Comment by threethan** [comment]
@Celine-COVEN 
To be clear, the name is fetched from the `android:label` property in the `application` section of the manifest. The package name (in this case `com.Albyon.FightBackPremiumPreAlpha` is only used if no `android:label` is set.

This behaviour is consistent with launchers for Android phones, so you won't see this issue with any phone apps.

Many Quest apps have a slightly (or in this case significantly) different label declared in their manifest. 

The next update will use store labels from [scraped data](https://github.com/threethan/MetaMetadata) when available, for consistency with the stock launcher. This will include most apps officially listed on the store, including all apps added to [oculusdb](oculusdb.rui2015.me).

**Comment by threethan** [comment]
Resolved in 8.0.0
