### ISSUE TITLE
[Feature Request] Always on keyboard

### ISSUE THREAD

**Issue by jowala** [threethan/LightningLauncher#156]
Some android apps work best with a keyboard. Sometimes these apps will have the ability to pop up a keyboard inside the app, but that will end up covering some portion of the screen.

It would be great if their was an option to have the virtual keyboard present at all times.

**Comment by threethan** [comment]
I've finally looked into this, and sadly it's not possible.

Manually showing the software keyboard in Android is per-activity, and requires a reference to the foreground activity.

For security reasons, Android does not make it possible to reference any activity other than your own.
