### ISSUE TITLE
[Feature Request] Optional shortcut to Lightning Launcher via Library

### ISSUE THREAD

**Issue by LivingBuzzard55** [threethan/LightningLauncher#159]
Basically instead of hovering over library, actually clicking the library button to open lightning launcher

**Comment by threethan** [comment]
This was previously a limitation with how the Quest's SystemUX handled accessibility events. It's recently been resolved and the behavior will be changed in the next update.

**Comment by LivingBuzzard55** [comment]
When could we expect this next update?

**Comment by threethan** [comment]
Resolved in 8.0.0
