### ISSUE TITLE
constant update

### ISSUE THREAD

**Issue by JarJarBlinkz** [threethan/LightningLauncher#16]
evrytime the launcher is opened it asks to update from 4.0.1 to 4.0.2 but does not update that is using the 4.0.2 release from yesterday

**Comment by threethan** [comment]
Should be fixed now. That update was put out in a hurry to attempt a bug fix. Now that a higher version is out you should be able to actually update.

Version 5 adds a proper option to hide these nags, so if I make a similar mistake again it shouldn't be anywhere near as annoying.

**Comment by JarJarBlinkz** [comment]
Superb work by the way maybe you can help fix one i was working one not
sure how to get it working again new to all this android stuff just learning
