### ISSUE TITLE
Option to open website in Meta Quest Browser not saving 

### ISSUE THREAD

**Issue by johlkien** [threethan/LightningLauncher#160]
When setting the universal option or for a specific webpage, the option to open in Meta Quest Browser does not save. Going back into settings shows it still listed as "open in Lighting Browser". This presents an issue for adding a webpage that has a VR Mode. Lightning Browser cannot enter VR Mode and so opening in Meta Quest Browser is needed.

**Comment by threethan** [comment]
Resolved in 8.0.0
