### ISSUE TITLE
[BUG REPORT] The app window is too small due to the v69 update so it needs adjusting to make it big again.

### ISSUE THREAD

**Issue by gaveitatry3** [threethan/LightningLauncher#161]
Recently, Meta changed the pixel density of apps so now non Meta app windows are a LOT smaller than they used to be. A user can resize the app window to make it bigger, but this is temporary. As soon as the user closes the app window and opens it back up again, the window will be tiny again. It's not a fun experience having to constantly resize an app window dozens of times over and over again. There is another app that I use called Quest Games Optimizer (QGO). When I told the developer about this problem, he immediately fixed it and made it so that the app window is always the same size as Meta app windows. So I am hoping that you will also do the same to your app sometime soon.

**Comment by threethan** [comment]
Resolved in 8.0.0
