### ISSUE TITLE
Advanced Settings

### ISSUE THREAD

**Issue by dafaithz81** [threethan/LightningLauncher#163]
To control the window behavior, you wrote:

"New features for Meta Quest OS v69 and above:
Enable this in Settings -> Advanced Settings

If one of the three main window spaces is available, the new window will be opened alongside the Lightning Launcher window, not replacing it

Apps set to use a specific window size will also open alongside the main launcher window!

When enabled, you can open multiple apps in custom-sized windows simultaneously"

I couldnt find anything about that in advanced settings.

**Comment by threethan** [comment]
This was an error in the release notes, based on an in-development version. This feature is enabled by default for eligible 2D apps on v69 and later.

I've removed the incorrect line from the release notes. I may decide to reintroduce this toggle in a future version.
