### ISSUE TITLE
"No apps can perform this action" when setting default home or installing addons

### ISSUE THREAD

**Issue by TyFinEsseinDieC** [threethan/LightningLauncher#165]
Thank you for your work, and the update. 

Issue: When I attempt to set lightning launcher as my default home, I get this error. It also occurs when I try to create/install a shortcut from the settings section [photo].

Version 8.0.0

QuestOSVer: V71 - Quest 3

![fd6cc5767170af97a61b589c8c56723d](https://github.com/user-attachments/assets/973a5259-4bdd-4ad3-8487-b7397859fef5)

https://github.com/user-attachments/assets/90ce8a40-778c-4c50-a977-e003b56a89e5

I also don't see the new window options under Advanced settings and I don't see any sizing options for any apps like before to select "medium" etc. 

~~Lastly the windows do not launch alongside lightning launcher. I had one experience when it almost did. The app [apkpure] launched correctly, prompting lightning launcher to close and lightning launcher reopened in one of the 2 available spaces.~~

**Comment by threethan** [comment]
> I also don't see the new window options under Advanced settings
This was an error in the release notes. In 8.0.0, side-by-side windows will be used by default on eligible versions.

As for the actual issue, I haven't been able to replicate it on my Quest 2 or 3, both on v71. 
Are you using the standard or PTC release channel?

It's possible that this is an issue with your installation or Android itself. Setting the default home is done in a pretty standard way that shouldn't break like this.

Issues like this can occur when disabling system packages, or occasionally as a result of unusual Android configurations. 

If anyone else has this issue, please let me know. If it's not too much trouble, include device, version, and a list of system tweaks or modifications you've performed. For any developers out there, logcat output may also be helpful.

**Comment by Juncoco94** [comment]
Same issue with PTC version 71.0.0.278.522 when trying to install shortcuts. I had developer functions on Android Settings, Also noticed on Android Settings > Apps > General Default apps (Theater Control Bar) when clicking on it it pops the same message 'Android System' window with 'No apps can perform this action'

**Comment by TyFinEsseinDieC** [comment]
> > I also don't see the new window options under Advanced settings
> > This was an error in the release notes. In 8.0.0, side-by-side windows will be used by default on eligible versions.
> 
> As for the actual issue, I haven't been able to replicate it on my Quest 2 or 3, both on v71. Are you using the standard or PTC release channel?
> 
> It's possible that this is an issue with your installation or Android itself. Setting the default home is done in a pretty standard way that shouldn't break like this.
> 
> Issues like this can occur when disabling system packages, or occasionally as a result of unusual Android configurations.
> 
> If anyone else has this issue, please let me know. If it's not too much trouble, include device, version, and a list of system tweaks or modifications you've performed. For any developers out there, logcat output may also be helpful.

I don't believe I've disabled any system apps. Also I'm not 100% sure on the installation being the reason, but it may be. The user below stated they're having the same issues on the same system version as myself so it may indeed be the culprit. I think v71 is currently only PTC though I could be wrong. BTW I haven't been able to set the default launcher since v69 I believe, whenever Meta added the seamless multitasking feature.

**Comment by TyFinEsseinDieC** [comment]
> Same issue with PTC version 71.0.0.278.522 when trying to install shortcuts. I had developer functions on Android Settings, Also noticed on Android Settings > Apps > General Default apps (Theater Control Bar) when clicking on it it pops the same message 'Android System' window with 'No apps can perform this action'

Same, although I've noticed this will also occur even when I was trying to install an app via "Update Me." So maybe it's not exclusive to Lightning Launcher and indeed just V71. As for setting the default launcher I haven't been able to do so since V69, but I didn't start seeing the error message until V71. I think the default launcher is checked SystemUX or something for me.

**Comment by threethan** [comment]
> Same, although I've noticed this will also occur even when I was trying to install an app via "Update Me." I am able to install apks still via CX File Explorer without getting this error so I dont think it's the system package installer.

This is extremely helpful, I'll try and figure out what that app does differently.

It's definitely a Quest-specific issue, even if it doesn't happen on every device. As such, it may take some time to resolve.

**Comment by dafaithz81** [comment]
Just tested it on my system: Im on PTC v71 too and had zero problems to install the shortcuts. Maybe you guys should list your installed third party apps. Im using xplore with shizuku for example, maybe some installed app changed the default package installer ?

**Comment by threethan** [comment]
The secondary issue with inconsistent launching should be resolved in 8.1.

I still can't replicate the main issue with installations failing. It may be the result of an A/B test on Meta's end. *(If that's the case, it will probably consistently work or not work for everyone when the next update drops)*

I'll keep looking out for this, and more reports are appreciated.
For the meantime, you can download and install updates through SideQuest and install shortcuts manually from [here](https://github.com/threethan/LightningLauncher/releases/tag/addons8.0.0). *(You'll still need to activate them)*

**Comment by TyFinEsseinDieC** [comment]
> Just tested it on my system: Im on PTC v71 too and had zero problems to install the shortcuts. Maybe you guys should list your installed third party apps. Im using xplore with shizuku for example, maybe some installed app changed the default package installer ?

Done. Note the circled apps were installed a few days after I reported the issue, so those can be ruled out immediately.![88280e7c8d058694cfc5c0c428cc2290.png](https://github.com/user-attachments/assets/39f546ac-2d69-473c-981d-95132963b877)

![1758fc0250aea605df0b44cbf9631c01.png](https://github.com/user-attachments/assets/023b73b8-9f0b-40e3-8fce-4f953861d18a)

![96832bc496d522579e5e94254b2d7110.png](https://github.com/user-attachments/assets/3cef1c9d-ae9e-4132-9bc3-ec5ecd96cac8)

**Comment by TyFinEsseinDieC** [comment]
> The secondary issue with inconsistent launching should be resolved in 8.1.
> 
> I still can't replicate the main issue with installations failing. It may be the result of an A/B test on Meta's end. *(If that's the case, it will probably consistently work or not work for everyone when the next update drops)*
> 
> I'll keep looking out for this, and more reports are appreciated.
> For the meantime, you can download and install updates through SideQuest and install shortcuts manually from [here](https://github.com/threethan/LightningLauncher/releases/tag/addons8.0.0). *(You'll still need to activate them)* 

Understood, and thank you. Also I've replied to a comment above with screens on my third party apps.

**Comment by threethan** [comment]
I have identified an additional issue, where you can't change the default home on v71. The dialog opens, for me, but doesn't work. It also doesn't work via ADB.

I've tried a number of possible fixes, but it seems that an update broke this functionality on a system level.

The "Set as default home app to enable 3rd party shortcuts" option will be disabled for v71 or newer in the next update. This only worked with a small minority of Android apps, anyways.

I am still investigating the package installation issue. If anyone who has this issue is willing to volunteer their time for more rigorous testing, let me know on [Discord](https://discord.gg/xG8EG2VxeS).

**Comment by Juncoco94** [comment]
I have APKPure and APKCombo Installer. not sure if I messed with Android Settings

**Comment by threethan** [comment]
Thanks to everyone for the input.

I have determined that the package installation issue is *not* the fault of Lightning Launcher, as it effects other apps including Android's built-in file manager.

If you have it, you'll either need to circumvent it with apps which use an older installation method. *(If it's really bothering you, it'll __probably__ be fixed by a factory reset)*

It *might* be related to something you changed or installed.
Most likely, it is either a bug in Meta's firmware, or an issue with some change they are A/B testing.

If it becomes reproducible, I will reopen the issue. Further info is still welcome.

**Comment by esc247** [comment]
hi, I am having the same issue as well where I see the No apps can perform this action message when trying to open yhe shortcut link
