### ISSUE TITLE
[Feature request] Window behavior

### ISSUE THREAD

**Issue by dafaithz81** [threethan/LightningLauncher#166]
There are basically 3 behaviors (window placement) allowed by the quest atm:
Make a new window right next to lightning, replace the lightning window or make it inside of the lightning window.
Atm Lightning wants to make a new window right next to the lightning window or replace the lightning window when theres not enough space. 
Ive made a video to demonstrate my problem/request: https://www.youtube.com/watch?v=R4eWvz-Bmac

Sometimes the new window spawns in the middle and lightning shifts to the left. Sometimes the new window spawns in the left and lightning stays in the middle. Sometimes the lightning window contains the new app but starts a new instance of it to the left. I find it too random.

My Suggestion would be: Make a default behavior in the settings (replace, make a new window or show it inside from the lightning window) and make it configurable on a per app basis, so that i can override the default from the setting.

Ive made another video from another app to show the bahavior: https://www.youtube.com/watch?v=0gA61lJOb2M
The german lables says (from left to right): inside, instead, besides.

This behavior, configurable in the app dialog
![com oculus vrshell-20241017-193515](https://github.com/user-attachments/assets/a4cf6ac9-dba4-41b5-979a-69bae1b2b276)

And the default behavior configurable in the settings
![com oculus vrshell-20241017-193639](https://github.com/user-attachments/assets/ca8b7f1f-b8a7-4989-9284-7efad41e3f5a)

Would be a good solution IMO

**Comment by threethan** [comment]
8.0 make the new window behaviour more reliable, and lets you turn it on and off.
It's not _quite_ as customizable as you suggested, but it should work well enough.
