### ISSUE TITLE
8.0.0: Apps don't always launch

### ISSUE THREAD

**Issue by demir-delic** [threethan/LightningLauncher#168]
Since upgrading to Lightning Launcher  8.0.0 on Quest 3, version 69, I've very frequently had the issue that the launcher closes without launching an app that was clicked on.

I open the launcher (directly or through People app shortcut), click on an app (can be anything - built in Meta app, Unknown Sources game, whatever), and the launcher closes itself without opening anything. If I open the launcher again and click that same app again, it then launches.

This behavior is intermittent, and I haven't been able to pin down the conditions when it occurs consistently. Sometimes I can open the Camera ten times in a row with no issue, sometimes I get the launch issue 3-5 times in a row.

**Comment by threethan** [comment]
Check if 8.1 fixes your issue. The default launching behaviour is now the same as version 7.

**Comment by threethan** [comment]
I have confirmed that 8.1 resolves launching issues with certain apps. If this did not fix your problem, leave a comment and I will reopen the issue.
