### ISSUE TITLE
Window management suggestion

### ISSUE THREAD

**Issue by marwan4mr** [threethan/LightningLauncher#169]
When opening app with custom window setting it opens in an instance of the launcher making it unavailable to open the launcher from  the dock 

I suggest that all custom window open in new app other than the launcher app (new apk like the shortcuts apk but for custom window only )  so we can open the launcher from the dock while custom window is open

Other suggestions is to open the targeted app in the middle and move the launcher to either of the side panels like the default launcher behavior

**Comment by threethan** [comment]
Turn on "Keep launcher window after opening apps" - I believe it matches your "alternative" suggestion. 
This was the default in 8.0, but it's now an option as it can occasionally cause its own issues.

I considered making an additional app for custom windows, but decided against it as this method works nearly as well and doesn't require downloading/installing/updating another app. If the keep launcher window method stops working at some point, I'll reconsider it.
