### ISSUE TITLE
Some settings (Such as Keep launcher window after opening an app) don't apply correctly when set from non-main window

### ISSUE THREAD

**Issue by LIU7899** [threethan/LightningLauncher#170]
The following 2D applications are "Open as Self Window"
    1.When the Lightning Launcher opens the 2D application, a new Lightning Launcher is generated.
    2.When 2 of the 3 windows are already in use, there is only one window left. Opening a 2D application with the Lightning Launcher will not work.

In version 8.1, opening a specific window with the Lightning Launcher fails to open the same specific window.So I use "Open as Own Window"

    Thank you for developing the launcher that made it so convenient for me to use Quest3.

**Comment by threethan** [comment]
I am having trouble understanding your issue, but I will try to address it the best I can.

When there is not enough free spaces to place the launcher window and the 2D window, the 2D app will not appear. This is expected and will not be fixed.

To avoid this, close another window or drag it outside of the three main spaces.

Tell me if I addressed your issue. Please give more information if I have not.

**Comment by LIU7899** [comment]
Thank you for your answer!
I closed "Keep launcher window after opening an app".
Lightning Launcher opens to create 2D by itself
app", the lightning launcher also regenerates, and I want to make it no longer regenerate.

**Comment by LIU7899** [comment]
https://github.com/user-attachments/assets/a0fa9a0b-8e5e-4ef6-9212-2308685f891f

**Comment by threethan** [comment]
Thank you. I have identified the issue and a fix will be coming in the next update.

For now, you may be able to open Lightning Launcher the the main icon with a white background, then turn the setting off from there.

**Comment by LIU7899** [comment]
I've tried modifying the settings of the main window (that white icon) and have the same issue in the video

**Comment by threethan** [comment]
Fixed in 8.1.1. 
*You still experience this issue, let me know and I will reopen this issue.*
