### ISSUE TITLE
[Request] Option to hide Quest Game Tuner promo banner

### ISSUE THREAD

**Issue by hikeri** [threethan/LightningLauncher#171]
I understand that many people might be interested in Quest Game Tuner and advertising is useful for its promotion. But if the user already knows that it exists and does not want to buy it, then you can hide the advertising, right? I think it's worth adding a button in the settings to disable the integration of Quest Game Tuner with lightning launcher

**Comment by threethan** [comment]
_C'mon, just give it a try!_ /s

In all seriousness, I understand that it can be annoying to suddenly see a promo somewhere you didn't before. Maintaining and supporting the Lightning Launcher takes time. Selling and developing Quest Game Tuner lets me continue improving LL for free. Version 8.0 and later use code originally developed for QGT, and wouldn't exist without it.

FWIW, I made sure to place the promo where it wouldn't take space from other other features.
