### ISSUE TITLE
Most Recent Update Does Not Launch

### ISSUE THREAD

**Issue by curvatura99** [threethan/LightningLauncher#172]
Just updated to the most recent version (8.1.2) and the apk doesn't launch. Rebooting the headset and/or reinstalling the apk doesn't help. Quest 3 with v69.

**Comment by curvatura99** [comment]
Installed version 8.0.0, imported the config files, and now everything is back to normal. I believe version 8.1.1 was working prior to the 8.1.2 update.

**Comment by threethan** [comment]
Issue occurs due to v69 and older's incorrect implementation of `android:Theme.NoDisplay`. Rolled back the change in 8.1.3 while keeping other improvements. Sorry for the inconvenience.

**Comment by curvatura99** [comment]
No problem. Thanks for updating so quickly.

**Comment by c-hri-s** [comment]
I'm runing 8.1.3 and it doesn't seem to want to launch anything. The app quits and takes me back to the standard app launcher.
