### ISSUE TITLE
[Feature Request] Time played

### ISSUE THREAD

**Issue by Ekidoxx** [threethan/LightningLauncher#173]
Could you please consider adding an option to see time spent in each game/app?
_QGO Premium Extension_ has this and it's nice, but even though I much more prefer LL for how clean and simple it is, I really miss this feature.

Example, from QGO:
![image](https://github.com/user-attachments/assets/b5773c1f-4853-436e-b7a9-b81f6d3e8c7b)

Bonus points if that info could be stored in some backupable file, so data wouldn't be lost on OS updates / could be copied before factory reset.

**Comment by threethan** [comment]
This feature is now implemented in Lightning Launcher 8.3.0! The playtime shows on hover.

If you also have [Quest Game Tuner](https://threethan.itch.io/quest-game-tuner/), you can also view a daily or monthly breakdown.
