### ISSUE TITLE
problem launching an application with LightningLauncher 8.14

### ISSUE THREAD

**Issue by April-ha** [threethan/LightningLauncher#174]
LightningLauncher 8.14 Quest-Game-Tuner 1.1.2 and V69

Hello,
To launch an application, I click once on the application icon, theLightningLauncher closes.
 I have to relaunch LightningLauncher to click on the icon again.
I often have to do 2 launches, but it's random, sometimes a single click is enough.

Thank you for your superb application.

**Comment by c-hri-s** [comment]
Same for me

**Comment by Ekidoxx** [comment]
I had this problem since I first discovered LL, which was in January 2024 on `Q2 v62` with `LL 6.3.0` - then I had to stop using the headset - and it still exists on `Q2 v69` & `Q3 v71 (PTC)` with `LL 8.1.4` installed.

It is unrelated to QGT, which, funnily, so far had no problem launching everything on first try.

**Comment by threethan** [comment]
This issue is very difficult to replicate. It's already been fixed for some people who were having it, but evidently not everyone.

Give 8.1.5 a go - I've resolved a possible race condition and added an additional fail-safe measure.

**Comment by Ekidoxx** [comment]
Works waaay more reliable, thank You, but occasionally still requires launching twice, which is really weird.

Funny downside of the latest fail-proof in `LL 8.3.5` is that launching website-shorcuts now almost always opens the link 3 times in oculus/lighting browser ^^'

**Comment by threethan** [comment]
Should be resolved for good in 8.2 _if_ you're on v71 _(v69 won't be getting a more proper fix at this point)_

If all goes well, this fix should also come to the next major update of Quest Game Tuner.

**Comment by Ekidoxx** [comment]
@threethan on `Q3 v71 (PTC)` website-shorcuts open either twice or not at all with "no app can perform this action" error (maybe will be resolved once v71 becomes official and not PTC), but other than that, everything launches flawlessly and indeed faster than before <3
