### ISSUE TITLE
Library shortcut does not work on v71

### ISSUE THREAD

**Issue by natebragg** [threethan/LightningLauncher#175]
My system just updated to v71 from v69.  On v69 the Library shortcut was working more or less as expected (open the library, and LL also launches in a separate window).  On v71, it does not launch at all.  I tried uninstalling the shortcut app, and reinstalling and activating it, but it did not make it work.

**Comment by Ekidoxx** [comment]
It's already listed in known issues of the latest release.

I'd suggest just pinning the launcher itself, instead of using shortcuts - you can unpin i.e. the camera app by dragging it down from the bar, and then once LL shows in the 3 latest used apps, simply drag its icon to the left to pin it.

**Comment by natebragg** [comment]
Whoops!  I read that but my eyes must have skipped that line.  Sorry!

Fair enough about the pinning.  I guess that's the solution.  It's a shame not to be able to replace the actual apps menu though.

**Comment by stanthewizzard** [comment]
Hello opening this issue
I only have 3 apps in the dock 
drag icon to the left doesn't pin it 
quest 3 v71

Am I doing it wrong ?
