### ISSUE TITLE
Button in LightningLauncher to refresh the list

### ISSUE THREAD

**Issue by April-ha** [threethan/LightningLauncher#177]
When I install a new apk it doesn't appear in LightningLauncher but in Quest-Game-Tuner.
I have to restart quest to see it in LightningLauncher .
Would it be possible to have a button in LightningLauncher to refresh the list.

**Comment by threethan** [comment]
In _most_ cases, the list will refresh automatically when a new app has been installed.

8.3.0 adds a button in `Settings -> Advanced Settings` to fully close Lightning Launcher.
When you reopen the launcher, it will refresh the app list *(and reload all your settings)*
