### ISSUE TITLE
[Feature request] Icons for sideloaded apps

### ISSUE THREAD

**Issue by lvonasek** [threethan/LightningLauncher#22]
Hi, would it be possible to add support for 3rd party icons repository? This is a pretty good one: https://github.com/Veticia/binaries

I am using your launcher mainly for sideloaded games/ports but for that the icons are not available.

Thank you in advance and keep going. You are doing a great job.

Luboš

**Comment by threethan** [comment]
Adding another repo wasn't too bad. Now Veticia's repo will be used at a higher priority than Basti's, but the latter will be used if no match is found on the former. You may need to clear custom icons or manually refresh each app to fetch the new icons.

Thanks for creating the original version of this thing :)

**Comment by lvonasek** [comment]
Awesome, thank you.
