### ISSUE TITLE
Quest 3 shortcut inconsistent 

### ISSUE THREAD

**Issue by HoriZon-nureekdotcom** [threethan/LightningLauncher#28]
As title have to click it a few times for it to work I have explore as my shortcut this is on LL v6

**Comment by threethan** [comment]
I don't have a Quest 3 but AFAIK the os should be similar to the Quest 2. 

The launcher does not open when you click, but rather when you hover over the icon long enough for the tooltip saying "Explore" to pop up. It's possible to very quickly click the button without actually activating the hover tooltip. Can you confirm this is not your issue?

It still takes a second or two to activate sometimes, so it may also seem like you need to trigger it twice but it would have actually opened anyways if you just waited.

If either of these are your problem, you can use the messenger shortcut instead. If not, please let me know and I will reopen the issue.

**Comment by HoriZonUK** [comment]
Yeah seems ok now if i hover it works all the time :)
