### ISSUE TITLE
Cannot scroll down the app list

### ISSUE THREAD

**Issue by MobButcher** [threethan/LightningLauncher#29]
After updating from 5.3.1 to 6.0.2, I've found myself unable to scroll down the list of apps I have. Every couple of frames the scroll position just resets to the top. This makes me unable to access most of my apps.

I have around 80+ apps in my folder/group, I have VR and TV apps shown as banners, and touching size or margin controls didn't help me out much, but I have 4 rows of 5 apps per row currently, 5 of which are pinned on top.

To be more specific, after I fully kill the launcher and launch it via Explorer Shortcut, the first time I drag the screen around it works mostly fine, but as soon as I release it jumps to the top and then the resets to the top start occuring.

Lightning Launcher 6.0.2 launched via Kotlin-less Explorer Shortcut Service Add-on on Oculus Quest 2 v57.0.0.261.669.517337457

**Comment by number875** [comment]
It worked for me in 6.0.1, but I can't find the file to downgrade

**Comment by bossman90** [comment]
Same here.

**Comment by Cygguu** [comment]
Same issue, was ok on 6.0 i think.

**Comment by jordanbelinsky** [comment]
Same here

**Comment by johnny2trayz** [comment]
> It worked for me in 6.0.1, but I can't find the file to downgrade

Sidequest still has an older version that works, I uninstalled the shortcut service, renabled the explore app, uninstalled lightning launcher and then installed it from Sidequest.

**Comment by carbonatedturtle** [comment]
I put off updating the first few times when I got the popup because I just wanted to hop into a game, but then I said "screw it, I'll just update now and get it out of the way!"

I didn't expect app breaking bugs at this point in this app's development, but I guess I'll wait a few days before hitting that update button next time.

**Comment by DevanWolf** [comment]
> It worked for me in 6.0.1, but I can't find the file to downgrade

Version 6.0.1 is now vaporware, I need the APK for it URGENTLY! It's not archived in Wayback Machine!

**Comment by johnny2trayz** [comment]
Version 5.3.1 from Sidequest
https://mega.nz/file/VCJhEQQb#WPQvrU5nv2nW5sSj9NRnrzbVLON3Ed5JX1KfdPOsWOM

**Comment by xkadafix** [comment]
you can use the search function as a sort of workaround

**Comment by threethan** [comment]
This was due to the quest randomly firing layout change events when it explicitly shouldn't have. Keep in mind this project is open source and currently just developed by me, but you can pretty easily build older versions. Either way, it should be fixed now.

**Comment by MobButcher** [comment]
Oh nonononono, sweetheart, I didn't mean it like that. I'm absolutely grateful for your work, and currently this is the only 3rd party launcher that I know of that is actually usable on Quest 2, and I've tried like five different ones. I love the work that you're doing and I cannot begin to express how much I appreciate the fact that you're maintaining this project and working on it, actively, in the present moment. Much love ❤️
