### ISSUE TITLE
Moving icons 

### ISSUE THREAD

**Issue by JarJarBlinkz** [threethan/LightningLauncher#3]
when moving icons to a new tab they stay selected and dont deselect once moved.

so when you move others icons to a different tab it moves all previous ones to the same tab as your moving new ones

**Comment by threethan** [comment]
Not sure what you are trying to say. Selecting icons, and then a tab, is the intended way to move them.

**Comment by threethan** [comment]
I figured out what the actual issue was. When moving apps, and then selecting new apps, the previous apps would become re-selected. Resolved as of 2.1.2
