### ISSUE TITLE
Hidden Groups not working

### ISSUE THREAD

**Issue by johnny2trayz** [threethan/LightningLauncher#30]
Some titles are auto hidden by default. Unable to unhide titles. Clicking "Restore all to default" hides even more apps and unable to unhide

**Comment by fmerlung** [comment]
At first I thought it didn't refresh the app list, but yeah it turns out some are just hidden by default. 
Toggling "Enable groups" on and off makes the group bar at the top glitch out and performance tanks immensely.

**Comment by threethan** [comment]
The "show" button currently moves apps to their selected default group. If no default is set for that type of app, they'll just be set to the hidden group again. I'm gonna update that so you it picks the first non-hidden group if no default is set.

Same deal with the resort to default groups button. Maybe I should add an additional button to reset the defaults? 

@fmerlung Nothing should be in the hidden by default, but if you updated from pre-6.0 you may have no default group set for TV apps, or may have deleted one of the default groups without setting a new default. Or are you referring to apps like meta quest move, which cannot be launched externally and don't show up at all.

**Comment by johnny2trayz** [comment]
Ah I see now. Alright the latest update has fixed any issues. Appreciate the work you do.

**Comment by threethan** [comment]
I've replaced the re-sort button with a popup that shows your default groups and gives you the option to reset those, just re-sort, or do nothing. This should hopefully clear things up.

The show button now tries to put apps into the first valid group if no default is set.
