### ISSUE TITLE
Feature Request: Set Window Size Per App

### ISSUE THREAD

**Issue by Risu** [threethan/LightningLauncher#31]
I've noticed that apps displayed in a launcher window are much sharper. 
When apps are using the resizeable concave switched view there is some bad blending like a bilinear filter or something.
After launching the android video player in the launcher window the playback quality is matching my TV and that is not reachable in the switched view.
 
Can you make a launcher window size more adjustable per app?
It can revert to whatever it was after app exiting, so it doesn't matter if it breaks anything in launcher UI temporarily.
I would be happy even with basic config loaded from a text file (like app name:size per line).

**Comment by threethan** [comment]
Unfortunately it doesn't seem possible to change window size programmatically, only to change the default size per-activity in android manifest. However, you can resize the LightningLauncher window, and I've already expanded the range far past the default. (Of course, you'd have to manually do this each time you open an app.)

It could potentially be possible to have a selection from a list of preset sizes, each having their own activity. However, other activities would have to close first so multitasking any window using that system would be limited similar to websites with open-in-own-window set. tl;dr: This would be clunky af

I haven't observed the sharpness thing you've mentioned myself, what device are you on?

**Comment by Risu** [comment]
Quest3, I didn't notice it too at first until I started comparing with reference material (MPV - MPV Desktop). I am using very high texture rendering buffer.

I can't resize LightningLauncher window in default view mode (flat), going from switched (curved), the window always reverting to the same size. There is a trick to change size?

The idea is to define multiple activities with different sizes (something like 720p, 1080p, 2160p etc) in the manifest and switch before app launch?

**Comment by threethan** [comment]
The flat view mode only uses the default size for the activity. Multiple activities may be possible, but would require a bit of work.
It's not as simple as just creating a new activity; the Quest will retain the window settings (including default size) for the activity first opened in the window, and does not respect requests to open an activity in a new window. This can be worked around only by closing all LL windows before opening the new one, which severely hinders multitasking.

I'll look into this further when I have time.

**Comment by threethan** [comment]
I've added this feature to 6.1. It's not perfect, but works better than I expected.

Let me know if there are additional sizes you'd like me to add, though I want to keep the overall count fairly low.
