### ISSUE TITLE
Apps' shortcuts support (the ones that appears on the android homescreen)

### ISSUE THREAD

**Issue by Risu** [threethan/LightningLauncher#33]
Some apps can create various shortcuts (not only webbrowsers) which appear normally on the android homescreen.
I would like to bind some scripts as shortcuts, but the LightningLauncher do not display them.

**Comment by threethan** [comment]
As of 6.1, apps can now add shortcuts to the launcher. You can also manually enter in intent URIs to the website input.

Note that you manually have to set Lightning Launcher as your home app for this to work. (there's a shortcut in advanced settings)

This isn't the same as the shortcuts that show up when you long-press an app on some launchers, but using an app like [Shortcut Maker](https://m.apkpure.com/shortcut-maker/rk.android.app.shortcutmaker), you can manually add similar.
