### ISSUE TITLE
New oculus explore

### ISSUE THREAD

**Issue by johnny2trayz** [threethan/LightningLauncher#34]
disabling explore removes icon from bar. I have also changed the "Default home app" and I don't know what the default is and it doesnt seem to affect anything.

**Comment by threethan** [comment]
That button is purely for adding shortcuts. I'll add a more prominent warning since I get that may be confusing.

What device/version are you seeing the explore icon disappear on? I'll change the text to indicate that you might not want to actually disable explore.

**Comment by threethan** [comment]
I've added relevant text explaining that explore may need to be re-enabled if the icon disappears, and what exactly setting the default home app does.
