### ISSUE TITLE
Most icons have been replaced or deleted

### ISSUE THREAD

**Issue by carbonatedturtle** [threethan/LightningLauncher#35]
The latest update decimated my icons, either replacing them with low-res and/or completely different versions or replacing them with the default icon that would normally only appear when an app had no icon, and these all previously had icons when I originally installed them.

**Comment by threethan** [comment]
This might happen when you aren't connected to the internet. The new update _shouldn't_ effect any custom icons you have set, but will attempt to redownload icons after install as there is now an additional icon repository. 

If you aren't connected to the internet, or if this is interrupted, icons may be left in an invalid state. Try clicking "Clear All Icons" in the settings when you have a good internet connection. _(Note that this will clear custom icon selections as well)_

**Comment by threethan** [comment]
Turns out the icon cache wasn't being properly cleared. Either use the fix above or wait for next update.
