### ISSUE TITLE
Can't add website unless explicity adding content scheme such as https://

### ISSUE THREAD

**Issue by mattios2001** [threethan/LightningLauncher#36]
Just installed, it's running fine. However, I cannot add a website, get 'Enter a valid URL and try again message', even with the default ones on buttons (discord/google etc)

Update: It works, you just need to add the https:// part to the URL. 

Discord works perfectly with this solution, amazing work, cheers :)

**Comment by threethan** [comment]
Silly oversight on my end! Fix is coming shortly
