### ISSUE TITLE
Explore shortcut no longer functions after rebrand of Explore to Oculus Explore

### ISSUE THREAD

**Issue by johnny2trayz** [threethan/LightningLauncher#38]
The icon for Oculus Explore displays as "Horizon Feed" when first starting the headset, followed by Lightning Launcher opening on it's own. The icon then displays as "Oculus Explore" and does nothing when hovering over, but opens Lightning Launcher if opened. If I open a vr app and close it, hovering over "Oculus Explore" does nothing and opening it does not open Lightning Launcher.

System update 50670960035200150

Version 59.0.0.138.706.530089545

Perhaps this is because of the old option allowing me to select a default home? I was unsure what the default option was and did not get a reply of what the default option was. Will uninstalling Lightning Launcher revert it to default? I can not find the option to change this variable anywhere else.

**Comment by johnny2trayz** [comment]
Since Lightning Launcher allows opening of system apps now, I have opted to use the Library option instead, which does indeed work.

**Comment by threethan** [comment]
This is because the name of the explore app changed. (Explore -> Oculus Explore)

As I already told you in your previous issue, the home app setting was only for allowing third-party apps to add shortcuts and doesn't have anything to do with this.

**Comment by threethan** [comment]
I've fixed this issue, please wait for the next release.
