### ISSUE TITLE
Discord no longer working

### ISSUE THREAD

**Issue by ItzDragonFace** [threethan/LightningLauncher#39]
As of latest update discord background audio does not work and will not allow the user to join any call. (All users appear offline).

Tested on Quest 2.

**Comment by chicaneau** [comment]
I am having the exact same issue

**Comment by threethan** [comment]
This is not an issue with any launcher updates, but rather with an update to the discord web app. I am unsure of the cause, but will continue to look into this.

Background audio continues to work in other websites.

**Comment by threethan** [comment]
I've resolved this by migrating to GeckoView. I need more time to test since it's a pretty major change, but a fix is on its way.

**Comment by ItzDragonFace** [comment]
Thank you

**Comment by chicaneau** [comment]
Man you move quick. Thankyou!
