### ISSUE TITLE
Shortcut apk broken by messenger update

### ISSUE THREAD

**Issue by niktn10** [threethan/LightningLauncher#4]
None of the easy app launch options work on the latest firmware.
Installed and uninstalled facebook, then installed your Optional-LauncherShortcut.apk. Writes that Facebook is not installed and does not launch the launcher.
Through the built-in option in the application, I also tried to enable the launch, but when you hover over the button, nothing starts. Although another launcher is launched through this function.

**Comment by threethan** [comment]
The shortcut apks overwrites Facebook _Messenger_, not standard Facebook.

Please explain what you mean by "Although another launcher is launched through this function."
What version of the Quest OS are you using?

**Comment by threethan** [comment]
Shortcut is more consistent in the latest version

**Comment by dexterwick** [comment]
How can I uninstall Messenger? I didn't found the package name to uninstall.

**Comment by threethan** [comment]
Please read the instructions thoroughly.

You need to install messenger from the oculus store (as you would with any official app) to register the package as an official app, which then lets you launch it from the main apps screen and pin it to the dock. After that you uninstall it, then install the shortcut apk.

**Comment by dexterwick** [comment]
> 

Sorry, I read the instructions and I have the messenger installed for a long time, and I have no option to uninstall it, I also did not find the name of the package to uninstall via adb, here is a screenshot (v51 here)
![IMG_3256](https://github.com/threethan/LightningLauncher/assets/40462051/f8284f46-0545-4ad6-8477-541016948e00)

Just saying, the v4.0 is amazing man! Thanks for your work!

**Comment by threethan** [comment]
Bizarre - that has a different icon that the version I have. What version of the quest are you on and what region are you in?
I'll look into this further when I have better internet. Seems like they've changes messenger to a system app. If that's the case it would be impossible to override, but I could just change the package name to a different app.

**Comment by dexterwick** [comment]
> Bizarre - that has a different icon that the version I have. What version of the quest are you on and what region are you in?
> I'll look into this further when I have better internet. Seems like they've changes messenger to a system app. If that's the case it would be impossible to override, but I could just change the package name to a different app.

I’m on v51 on quest 
Europe 
No way to replace the explore app? 

But hover on all apps working perfectly apparently, I didn’t tested too much

**Comment by threethan** [comment]
You're quite a few versions behind, maybe that's why? I'm also in the US so there could be regional differences with Facebook services.

The explore app is a system app and cannot be replaced. It's would be possible to open the launcher when you hover the explore icon, similar to how you can open it now by hovering the library, since that emits an accessibility event.

The shortcut apk works by imitating the package name of messenger, so the Quest registers it as a modified version of messenger instead of something completely different. Messenger was a completely arbitrary choice, any free & uninstallable non-vr app on the store would work. I just liked the Messenger icon lol

**Comment by dexterwick** [comment]
I decided to disable the update after what happened when I updated to v51 which broke all the games, but days later I already had a solution but I preferred to stay that way, I saw that it works the way you said, for now I will use it that way, thanks again for the your job!

**Comment by threethan** [comment]
Since this works on the latest version, and alternatives are available for earlier versions, I'm just gonna close this issue.
