### ISSUE TITLE
Explorer shortcut is not functional in Chinese

### ISSUE THREAD

**Issue by dabinn** [threethan/LightningLauncher#40]
Explorer shortcut is not functional when the system is set to display in Chinese. There is no response, whether hovering or clicking. However, the message shortcut works fine.
If the system language is set to English, everything works as expected.

**Comment by dabinn** [comment]
I checked the code, found a strings.xml file in values-zh-rCN.
But there is no strings.xml for trandition Chinese e.g. values-zh-rTW and values-zh-rHK.

**Comment by dabinn** [comment]
Issue fixed, I added 2 additional 'values-' in res directory. I'll create pull request tomorrow.

**Comment by threethan** [comment]
Accepted to the PR, will build once I've finished fixing quest-update related issues
