### ISSUE TITLE
Messenger Shortcut open phone-sized window in v59

### ISSUE THREAD

**Issue by JarJarBlinkz** [threethan/LightningLauncher#42]
2D sideloaded Android apps are now locked in a vertical smartphone aspect ratio. it used to default to a “tablet” aspect ratio but now if you resize and then close it and reopen it goes back to vertical smartphone aspect ratio

**Comment by threethan** [comment]
For whatever reason, the same shortcut works as previously if overloading com.facebook.facebookvr, so that will replace the messenger shortcut in the next release.
