### ISSUE TITLE
Open in window and PinShortcut

### ISSUE THREAD

**Issue by tikimesh** [threethan/LightningLauncher#45]
The new open in own custom size window is nice, another size would be usefull. Something between the default size and Large 16:9. For quest2 about 1024 window width with the same aspect ratio as the default window, or something along those lines, not sure about how that translates to Q3 though.
Another feature request would be to enable PinShortcut. When I try to add a shortcut through "Activity Launcher" android app it says your launcher does not support PinShortcut. I suspect the same limitation keeps me from adding shortcut widgets from browsers for example Mull or Vivaldi have options to add shortcuts to the android home screen, these just fail silently. Completely understand if this is out of scope, unfixable or too much work.
Thanks for the awesome launcher

**Comment by threethan** [comment]
Pinning shortcuts from a browser is a system limitation, not a limitation of the launcher. If you run the launcher on a normal android phone this works just fine.

You can work around this by using an app like [Shortcut Maker](https://www.apkmirror.com/apk/android_rk/shortcut-maker/shortcut-maker-4-2-3-release/), or you can manually input intent URIs if you know what you're doing.

As to adding another size, sure lol.
