### ISSUE TITLE
Change "Display as Banner" Setting Removes All Customized Icons

### ISSUE THREAD

**Issue by frankiewu1985** [threethan/LightningLauncher#46]
To repro:
- Open Settings
- Under "Display as Banner", toggle Panel Apps to show or not show it as banner.
- All custom icons are lost.

I think this should be a easy fix to who are familiar with the code, otherwise wouldn't mind to take a look myself when I got time.

It's a great launcher and I really like it :)

**Comment by threethan** [comment]
The actual issue seems to be that `Compat.clearIconCache()` either clears custom icons, or causes icons to be overwritten.

This would ideally be fixed by placing the cache for custom icons and in a separate directory from the normal icon cache, and searching there first.

**Comment by threethan** [comment]
Fixed this and some related issues in 6.2.1
