### ISSUE TITLE
How do I change icon/banner from my computer to lightningLauncher?

### ISSUE THREAD

**Issue by think2011** [threethan/LightningLauncher#47]
The refresh icon/banner seems to be not working.. so I want to upload icon from my computer to the lightningLauncher. 

However, I've found lightningLauncher only allows selecting images taken by the Quest media. 

Could you tell me what should I do? thanks.

**Comment by threethan** [comment]
Place the image file in any folder in your device's shared storage using adb push or MTP, then select it from the image picker.

**Comment by think2011** [comment]
![23333333333](https://github.com/threethan/LightningLauncher/assets/3961388/9fee38f1-83d5-4191-983f-6fd441fe0469)

https://github.com/threethan/LightningLauncher/assets/3961388/9d37a97b-ecab-485a-a9ac-06c79c72bf8f



@threethan  Still not working, I tried to place the above 2 folders still not working.. 
Another thing is that icon still cannot download, It may be compatible with Quest3? 

version: 6.2.0 (from SideQuest)
device: Quest3

**Comment by think2011** [comment]
I'm sure I don't have any problem with my network. I can visit Google or YouTube very fast on the Quest 3 browser

**Comment by think2011** [comment]
> ![23333333333](https://user-images.githubusercontent.com/3961388/279660426-9fee38f1-83d5-4191-983f-6fd441fe0469.jpg)
> 
>  2222.mp4 
> @threethan Still not working, I tried to place the above 2 folders still not working.. Another thing is that icon still cannot download, It may be compatible with Quest3?
> 
> version: 6.2.0 (from SideQuest) device: Quest3

Oh, Sorry. When I go to File app and clicked sync,  the images did indeed shown on

**Comment by threethan** [comment]
Glad you figured it out. As for icons not downloading, try clicking "Reset All Icons" in the settings and see if that fixes it. Sometimes they can get "stuck" if a download is interrupted.

**Comment by think2011** [comment]
<img width="719" alt="image" src="https://github.com/threethan/LightningLauncher/assets/3961388/345c53e3-0042-4ee3-bbc2-63983228d45b">

When I updated to 6.2.1, banner images has been automatically downloaded,  it's working well, thanks!
