### ISSUE TITLE
Installing/Uninstalling

### ISSUE THREAD

**Issue by mrzoops** [threethan/LightningLauncher#5]
I previously had an earlier version of this installed. I have uninstalled it, but when trying to install the new version I am still getting an error regarding the previous version signature. I do not see the old version installed anywhere. Anyone know where I can completely clear the quest of the old version?

After more testing, I tried installing the standard Messenger app from the app store to hopefully overwrite anything, but that install is also failing. It downloads and says installing, then changes to Not Installed. Something is completely borked.

**Comment by threethan** [comment]
The launcher shortcut and the launcher are two separate applications. Have you uninstalled both?

You can try the following adb commands to uninstall:
`adb uninstall com.threethan.launcher` to uninstall the launcher
`adb uninstall com.facebook.orca` to uninstall the messenger shortcut

**Comment by mrzoops** [comment]
Thank you. That worked.
