### ISSUE TITLE
Browser Fullscreen Video

### ISSUE THREAD

**Issue by alexyao2015** [threethan/LightningLauncher#53]
Is there anyway to get the browser to have the option to use the native quest full screen popup? If its not possible with Firefox, is it possible to have the ability to select between the default android webview and firefox? I'm guessing that the firefox view doesn't support fullscreen content in the native viewer.

**Comment by threethan** [comment]
IIRC this didn't work on the system webview either. Definitely didn't on YouTube.
You can always open the default browser or wolvic from LL to view VR content.
The built in browser is meant mainly for background audio on quest, or for TVs where a normal browser won't work.

**Comment by threethan** [comment]
Can you confirm whether this is a regression?

**Comment by alexyao2015** [comment]
I haven't used any of the old versions, but I believe you when you say it didn't work before. Perhaps another idea is it could launch the default browser with the url. I'm away from my headset now, so I can't test this, but I'm curious if other phone browsers are able to play full screen video (e.g. on YouTube).

**Comment by threethan** [comment]
This would be nice to add, but it's not planned as of now
