### ISSUE TITLE
Icons for some official apps are missing

### ISSUE THREAD

**Issue by Iftuga** [threethan/LightningLauncher#58]
Are icons for official apps being downloaded from some repository, or are they fetched from the apps themselves somehow?
I am missing icons for some official apps, so in the case of the second option, I guess it is a bug
The apps in question are "First Encounters" and "First Hand"
I am using Quest 3 if it is relevant

**Comment by threethan** [comment]
Icons for VR and panel apps are fetched from icon repositories. If that fails, the package icon/banner is used. In many cases, such as this, these are just default game engine icons. 

Feel free to make an issue in any of the icon repos, including [mine](https://github.com/threethan/QuestLauncherImages).
