### ISSUE TITLE
Resize launcher window

### ISSUE THREAD

**Issue by c-hri-s** [threethan/LightningLauncher#59]
I use the launcher in place of Facebook Messenger and recently it has reverted from being a square wide window to a narrow portrait window.

Please could you add an option to go back to the old size? I have quite a few apps and it's easier to browse if more are displayed on the screen

Thanks for the great launcher!

**Comment by threethan** [comment]
Use the new Facebook Shortcut, this is a known issue specifically with the old messenger shortcut which is no longer supported for this reason
