### ISSUE TITLE
Move app to -hidden crashes launcher

### ISSUE THREAD

**Issue by samwyze** [threethan/LightningLauncher#6]
Whenever I try to move an app to the hidden tab the launcher crashes. Upon reopening the app has not been moved. v2.1.1.
Quest 2 v56.

**Comment by threethan** [comment]
Resolved in 2.1.2

**Comment by ConSolatory** [comment]
crashes  and hidding and always starts only in phone mode.  After stretched to the screen - the next launch will still be in narrow window mode with 2 rows only. Settings are not saved.
