### ISSUE TITLE
Choppy/Glitchy Audio on Discord while Launcher is not in the Foreground

### ISSUE THREAD

**Issue by nixmars** [threethan/LightningLauncher#60]
Whenever I do a discord call from the website, the audio is VERY glitchy. I can barely hear my friends. Please tell me how to fix this! (on the quest 2)
Youtube audio is good for some reason, though.

Edit: Thanks for replying. Now I know that I'm not the only one with glitchy Discord audio. I forgot to mention that the glitchy audio only happens when I am outside of the app.

**Comment by JacobGonzalez0** [comment]
Audio is also glitchy for me in the Quest 3

Does not matter if any options are changed in Discord, audio on the mic is glitchy and so is recieved audio. Maybe something to do with WebRTC?

**Comment by polyzium** [comment]
Same issue. Discord on the Quest seems to be getting more dodgy every single day.

**Comment by threethan** [comment]
What OS version are each of you on? I assume LL is up to date?
Can you also confirm that a persistent notification from LL appears on the notification page while a website such as discord is running?

I had this issue briefly after first migrating to geckoview, but fixed it (for myself, at least) by increasing the priority of the background process.

I'm on the latest PTR and do not have this issue, though I do sometimes experience significant latency (up to 3 seconds) on discord calls.

**Comment by polyzium** [comment]
> What OS version are each of you on?

v59

> I assume LL is up to date?

Just launched and got a prompt to update to 6.2.2.

**Comment by nixmars** [comment]
> What OS version are each of you on? I assume LL is up to date? Can you also confirm that a persistent notification from LL appears on the notification page while a website such as discord is running?
> 
> I had this issue briefly after first migrating to geckoview, but fixed it (for myself, at least) by increasing the priority of the background process.
> 
> I'm on the latest PTR and do not have this issue, though I do sometimes experience significant latency (up to 3 seconds) on discord calls.

The notification _does_ run in the background, and it says that it keeps the audio smooth. The audio is in fact not smooth, and glitches in the foreground. When I am on the lightning launcher, the audio is smooth and clear with a few minor glitches. I'm on the latest update, and I don't know if this matters, but I got it from sidequest on my VR headset. Thank you!

**Comment by threethan** [comment]
6.2.2 shouldn't change anything related to audio. The notification indicates that the audio is running as a foreground service, which is the highest priority possible on Android for an app that's not actually in the foreground. 

Can you check if other websites work okay in the background? Discord, for some reason, seems to be especially demanding

I will look into this further when I have the time, but it may not be possible to improve this more.

**Comment by polyzium** [comment]
I tested this again, the audio is still choppy, at least on a Quest 2.

**Comment by threethan** [comment]
Started happening on my device - not sure what changed to trigger it.

Try giving [this patcher](https://github.com/threethan/QuestAudioPatcher) a try as an alternative. It works on the proper app version of Discord, though you'll need to use an [old version](https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-126-21-stable-release/discord-talk-chat-hang-out-126-21-stable-android-apk-download/download/?key=524e8c97e18586f13183d87e42aaa18914bcbb38) to prevent unrelated UI bugs.

**Comment by FrozenAlex** [comment]
> Started happening on my device - not sure what changed to trigger it.
> 
> Try giving [this patcher](https://github.com/threethan/QuestAudioPatcher) a try as an alternative. It works on the proper app version of Discord, though you'll need to use an [old version](https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-126-21-stable-release/discord-talk-chat-hang-out-126-21-stable-android-apk-download/download/?key=524e8c97e18586f13183d87e42aaa18914bcbb38) to prevent unrelated UI bugs.

Does not seem to work on q3. It just says that the package is invalid when I try to install the patched apk

**Comment by threethan** [comment]
@FrozenAlex Would greatly appreciate if you could create an issue on https://github.com/threethan/QuestAudioPatcher so that I may fix the issue. This will be the solution for Discord on Quest moving forward.

**Comment by FrozenAlex** [comment]
> @FrozenAlex Would greatly appreciate if you could create an issue on https://github.com/threethan/QuestAudioPatcher so that I may fix the issue. This will be the solution for Discord on Quest moving forward.

I'm planning to make a patch for ReVanced. They seem to allow device specific patches

**Comment by threethan** [comment]
That could work also but it's very similar under the hood my own AEE-based patcher (albiet *much* more complicated). It works on an Android phone and Quest 2 - so I'm unsure why it would be broken specifically on Quest 3.

**Comment by Shirk** [comment]
I can reproduce the issue while in a Jitsi voice call via LL and running another app in the foreground.
Audio quality isn't "bad" but there's regular, noticeable crackles for incoming and outgoing audio.

On it's own Jitsi is pretty low-demand compared to full blown discord so If there's anything I can do to help pin this issue down I'm happy to do so.

(testing on a Quest3 running the latest v60 update)

**Comment by threethan** [comment]
This seems to be an issue with geckoview running with background restrictions. The same issue is present, albeit to a much lesser degree, when running discord through Firefox on an Android phone.

Try using [my patcher](https://github.com/threethan/QuestAudioPatcher) on the native app for Jitsi, and let me know if there are any issues.

I do not think it will be possible to fix this, but I'll continue to leave the issue open for discussion.

**Comment by threethan** [comment]
As the browser is now its own app, this issue is no longer relevant. From now on, issues with the browser should be opened in https://github.com/threethan/LightningBrowser.
