### ISSUE TITLE
Audio issues with Discord

### ISSUE THREAD

**Issue by Rilyuzumaki** [threethan/LightningLauncher#61]
I could have made a misstep during my setup or something but after downloading lightning launcher from sidequest I got a prompt to update to 6.2.2, which ofcourse, i did. This is my first time using LL but when I enter a discord call with my friends and try to open a game, discord doesn't stay open in my background. Not only that but also when i open discord in the foreground my friends complain that my audio sounds choppy/glitchy. Like I said I could be doing something wrong but if anyone could throw an assist my way that would be sick

**Comment by threethan** [comment]
Try giving [this patcher](https://github.com/threethan/QuestAudioPatcher) a try as an alternative. It works on the proper app version of Discord, though you'll need to use an [old version](https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-126-21-stable-release/discord-talk-chat-hang-out-126-21-stable-android-apk-download/download/?key=524e8c97e18586f13183d87e42aaa18914bcbb38) to prevent unrelated UI bugs.

**The patcher is experimental - please let me know if it works or create an issue on https://github.com/threethan/QuestAudioPatcher if it does not!**

**Comment by threethan** [comment]
Try the patcher or refer to https://github.com/threethan/LightningLauncher/issues/60 for discussion.
