### ISSUE TITLE
Facebook (beta) removed from meta quest store, shortcut no longer visible

### ISSUE THREAD

**Issue by SahajJain01** [threethan/LightningLauncher#64]
The facebook app shortcut has disappeared from the Quest launcher and on the Store, Facebook (beta) cannot be installed since "Get" button is greyed out.
Is it possible to add this shortcut proxy as another app other than facebook?

**Comment by ImMock** [comment]
I just installed the Launcher, and the Facebook Shortcut its not being installed

**Comment by JarJarBlinkz** [comment]
they removed facebook for Meta Quest 2

![com oculus shellenv-20231129-195451](https://github.com/threethan/LightningLauncher/assets/104454560/2012f238-0bd1-47c1-b7c0-8e1e75c1ffcd)

**Comment by threethan** [comment]
How annoying. I don't have this problem on my Quest 2, so it might be a regional thing?
I can pretty easily set it override another 2D app available in the store.

Does anyone have a preference on which app should be overridden instead? I'm thinking Spike email might make sense. It hasn't been updated in years, so it's unlikely to break. Instagram (beta) could also work.

**Comment by SahajJain01** [comment]
So it seems to be back but it was gone 2 times like this on my Quest 3.
I would say it would be really helpful if you can add 1 or 2 more app shortcuts like facebook beta so people can choose whichever works for them.

**Comment by c-hri-s** [comment]
Same experience here. It vanished from the store for a few days but has now come back.
As above, it would be great if there could be a couple of extra options in case something like this happens again (or if someone wanted to use Facebook) - thanks

**Comment by threethan** [comment]
I'll add an additional option in the next update. Feel free to suggest which app should be overridden.

**Comment by c-hri-s** [comment]
Spike email sounds good to me. Never heard of it and can't believe anyone is using it if it hasn't been updated forever

**Comment by SahajJain01** [comment]
Just wondering if it would be possible to have a app launcher icon instead of the actual icon of the app.
Its a nice to have feature so that instead of facebook/spike icon there is an app launcher icon

**Comment by threethan** [comment]
> Just wondering if it would be possible to have a app launcher icon instead of the actual icon of the app. Its a nice to have feature so that instead of facebook/spike icon there is an app launcher icon

The default app library/dock only shows apps which exist on the Meta Quest store, and uses icons from the store, not the app itself. Sideloaded apps only show up in the 'Unknown Sources' menu. That's the main reason this app exists - to combine sideloaded and official apps. Spoofing the package name of an official app makes it possible to open from the main screen or dock.

**Comment by threethan** [comment]
Spike got delisted, so I'm using monday.com (another unpopular productivity app) as an alternate shortcut in the next version.
