### ISSUE TITLE
[Feature Request] Screen share from Discord web

### ISSUE THREAD

**Issue by ElectricFighter** [threethan/LightningLauncher#66]
Would it be possible to add support for screen share from Discord web?

AFAIK [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API) is not implemented for mobile devices but it could be possible to use a screen caputre service running on the launcher and create a MediaStream to use with [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) of the [Media Capture and Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API) that I believe is already used to grant microphone access.

If it's not possible to create a screen share MediaStream maybe a "fake" camera stream could work too.

It would be great to have this feature due to the limited mirroring capabilities of the Quest.

**Comment by threethan** [comment]
Screen capture does not work on the Quest, period. Neither does camera. I'd also love this feature, but it's not possible unless fixed on as OS level.

**Comment by ElectricFighter** [comment]
I should have guessed that it's locked on the OS side. What a shame, I hope eventually they'll at least give the possibility to stream to a public/shareable link. Thanks for the clarification
