### ISSUE TITLE
[Feature Request] Location permission support in browser

### ISSUE THREAD

**Issue by DevanWolf** [threethan/LightningLauncher#69]
Needed for Hulu to work on LL Browser

**Comment by DevanWolf** [comment]
Wolvic and Reality Browser don't have location permissions either so Hulu is not guarenteed to work on those other browsers.

**Comment by threethan** [comment]
Thanks for checking. What about normal, 2D Firefox?

I'll add this if I ever get around to adding a proper permissions system, but I'd rather not bother if it doesn't actually fix anything. For now, just use the MQ browser or android app for anything which requires location.

**Comment by DevanWolf** [comment]
> Thanks for checking. What about normal, 2D Firefox?
> 
> I'll add this if I ever get around to adding a proper permissions system, but I'd rather not bother if it doesn't actually fix anything. For now, just use the MQ browser or android app for anything which requires location.

Meta Quest Browser just refuses to get through the "Checking location" screen on Hulu although the browser's location permissions are enabled. Disney+ works fine on both Meta Quest Browser and LL Browser.

**Comment by threethan** [comment]
In that case, I'm guessing hulu is performing some other form of device verification when it really just says checking location. If it doesn't work there, it probably won't work in Firefox mobile. If it doesn't work in Firefox mobile, it definitely won't work in the LL browser.
The quest supports most - but not all - DRM protected content. It's possible that Hulu uses a form of DRM which is not supported  by on the quest.

**Comment by threethan** [comment]
I'm going to close this as not planned because I'd rather not hand out location permissions, and I'm pretty sure the Hulu problem is a DRM or device verification issue.

**Comment by DevanWolf** [comment]
But wait, it's needed for Google Maps to detect where your current home location is.
