### ISSUE TITLE
Crashing when "Magnification" is turned on

### ISSUE THREAD

**Issue by threethan** [threethan/LightningLauncher#71]
Im having the same issue when Magnification is turned on. Can't get the app to open anymore - no matter what I do

_Originally posted by @moni11811 in https://github.com/threethan/LightningLauncher/issues/63#issuecomment-1846109939_

**Comment by threethan** [comment]
@moni11811 You mentioned this in an unrelated issue. Can you please elaborate on what you mean by "Magnification"? No such option exists on my Quest 2 or Android TV box.

**Comment by moni11811** [comment]
@threethan that's Understandable although it sounded like the same. Im on Quest 3 V59 Launcher>Settings>Accessibility>Magnification
After turning that option on all my 2D Android Apps stopped working and would restart the device when opened. 
The problem was resolved however by resetting the device

**Comment by threethan** [comment]
"all my 2D Android Apps stopped working" In that case, it's not specific to LL. Glad you got it fixed.
