### ISSUE TITLE
What are the specific use cases of “set Default Home To Enable 3rd-party Shortcuts”?

### ISSUE THREAD

**Issue by blass0009** [threethan/LightningLauncher#72]
I tried to find some wiki or documentation but failed.
What is the specific usage of this function?
I read the important info but didn't understand it.
I set LL as the default launcher to see what would happen. Now I want to change it back in case I break something but I don't know what the original default launcher was. Any ideas?

**Comment by threethan** [comment]
The original default setting is VRShell. 

Setting this option to LL allows applications to place icons onto the launcher. 

If you have used an Android device, you may have added a website or app action to your home screen. This enables that same functionality on the Quest. Note that the default app library does not support this.

This is not an issue with the app, but I hope this helps. I might try to make the info pop up more clear in the future - let me know if you have any suggestions.
