### ISSUE TITLE
Fullscreen sites (sometimes) don't appear correctly; cut off screen

### ISSUE THREAD

**Issue by DevanWolf** [threethan/LightningLauncher#73]
![Proof](https://github.com/threethan/LightningLauncher/assets/8494722/a12345d3-ddda-45bc-a346-455ffcf877c0)

**Comment by threethan** [comment]
That's unfortunate. The fullscreen functionality is currently provided by GeckoView, so I'm not sure if I can improve it.

**Comment by threethan** [comment]
Going to close this since it's a pretty minor bug and it's likely an issue with geckoview.
