### ISSUE TITLE
Ability to open sites in Custom Tab (instead of standard Meta Quest Browser)

### ISSUE THREAD

**Issue by DevanWolf** [threethan/LightningLauncher#74]

**Comment by threethan** [comment]
The Quest does not support chrome custom tabs, I've checked. 

It is possible to open something that looks similar to a custom tab by launching a web intent in the normal way; however the window which pops up cannot be manipulated and hides all other windows, it's a paired-down (and potentially confusing) version of the Meta Quest browser. I don't plan to add that as an option as I don't really see a use case.
