### ISSUE TITLE
V60 update broke the App library shortcut, you have to use other shortcuts to open Lightning Launcher

### ISSUE THREAD

**Issue by pinguluk** [threethan/LightningLauncher#76]

**Comment by DevanWolf** [comment]
The new name is now "**Library**"

**Comment by keld107** [comment]
What does "the new name is now "Library" mean?" thanks!

**Comment by pinguluk** [comment]
> What does "the new name is now "Library"" mean? thanks!

I don't know either

**Comment by threethan** [comment]
"App Library" is now just called "Library". Since the shortcut service relies on the exact name of the app, it must be updated.

**Comment by keld107** [comment]
how do i update my apk? not sure what to do here? sorry!

**Comment by pinguluk** [comment]
> how do i update my apk? not sure what to do here? sorry!

Best way is to wait for 6.2.4 release (you'll get an update in the app to download it) or you can compile the project by yourself with the included fix.
Until then you can use an alternative shortcut

**Comment by threethan** [comment]
Update is live.

**Comment by pinguluk** [comment]
> Update is live.

Great work! Does it have backwards compatibility with devices under v60?

**Comment by keld107** [comment]
Thats amazing! nice work!

**Comment by threethan** [comment]
> > Update is live.
> 
> Great work! Does it have backwards compatibility with devices under v60?

This particular update should not break compatibility.
