### ISSUE TITLE
"Open in Meta Quest Browser" broken in latest update of Meta Quest Browser

### ISSUE THREAD

**Issue by DevanWolf** [threethan/LightningLauncher#77]
Now the sites from the launcher open the start page instead of the expected site.

**Comment by threethan** [comment]
It still works for me.
I assume I have yet to receive the breaking update, will check back periodically.

**Comment by threethan** [comment]
I'm still unable to replicate. What version is your Meta Quest Browser? Mine is on 30.3.0.17.55.54898615

This might have something to do with the configuration of the browser itself. What device are you on?

**Comment by threethan** [comment]
I am going to close this issue. Will reopen if it can be replicated.
