### ISSUE TITLE
LL missing newly installed applications after V60 update

### ISSUE THREAD

**Issue by Shirk** [threethan/LightningLauncher#78]
I don't know much about the internal workings of LL and how it collects the installed applications but it seems that since the v60 update on Quest3 it's missing a few apps that the normal launcher shows just fine.

current examples:
- XBox Cloud Gaming (beta)
- VRChat

**Comment by threethan** [comment]
VRChat _should_ display properly. Make sure it's installed, and not just on your account. Then try `Settings -> Groups -> Reset All Groups & Sort to Default`.

XBox Cloud Gaming is actually a progressive web app under the hood. Haven't yet figured out how to get those to properly open.

**Comment by Shirk** [comment]
Check, I had to Reset & Sort and everything but XBox Cloud Gaming is listed properly.

I hope you'll eventually figure out how to work with PWA's - it's only reason to leave lightning right now.

Closing this as my original issue wasn't really one!
