### ISSUE TITLE
Integrate Library/Horizon Feed/People/Store accessibility shortcuts into app as well as support for custom shortcuts by specified name

### ISSUE THREAD

**Issue by DevanWolf** [threethan/LightningLauncher#79]
It'll be more nicer to have the accessibility shortcuts that open the launcher be in the launcher app itself like PiLauncher did rather than having separate apps. Also custom shortcut support will work for example: if you have Echo VR pinned in your universal menu, input "Echo VR" (no quotes, which should parse the accessibility event name as [Echo VR]) into the custom shortcut creator dialog box, and now hover over the Echo VR icon and it will open Lightning Launcher that way!

**Comment by threethan** [comment]
"Integrating" the shortcuts would mean users have to re-activate each shortcut service every time the main app updates. It would also make multitasking impossible, as the Quest only allows for one window per package.

The customizable idea would work, but I just don't really see a good use case for it, and it would most likely just end up confusing people.

**Comment by DevanWolf** [comment]
> The customizable idea would work, but I just don't really see a good use case for it, and it would most likely just end up confusing people.

I just modified the accessibility_event_name string on the People or Library shortcut APK anyway.
