### ISSUE TITLE
Shortcut for App Library not working V60

### ISSUE THREAD

**Issue by Linkshaender** [threethan/LightningLauncher#82]
Hello Everyone,

I recently updates to V60 on Quest 3. I have never used Lightning Launcher before.
After installing and trying to set up shortcuts it seems that I can make every shortcut work, except the one for the App Library.

The Shortcut just shows up as a different app under unknown sources.

What other information do I need to provide for the fix of this problem?

Thank you and kind regards

//Edit: I saw the recently closed issue about the rename of the App Library to Library. I opened a new issue because I installed the newest version of LL and it still doesn't work. 6.3.0

**Comment by ElementalWerewolf** [comment]
same problem please fix. sometime when I try to launch a app on lightning launcher it wont launch the app

**Comment by threethan** [comment]
Have you gone into `Settings -> Shortcut Settings` and updated, then re-enabled the App Library addon? This must be done manually after the launcher is updated.

If you have, could you please tell me what exact text shows up when you hover the Library/App Library icon?

**Comment by Linkshaender** [comment]
Hi there, sorry for the late response.

I did updated and re-rnabmed the app library add-on. It simply shows up as a new app in the app library under unknown sources but the shortcut itself doesn't work. Other shortcuts like from people are working.

When I hover over the icon it simply says "App Library". The language of my headset is German, can this be an issue?

**Comment by threethan** [comment]
That would do it! It's expected to either show "Library" or show "App Library" *translated to your language.* Since it's displaying in "App Library" in English, despite your device not being set to English, it is not working. I will push an update to also detect that string. Thank you!

**Comment by ElementalWerewolf** [comment]
mi having the same ussue but im in english and updated to the newest update

**Comment by ElementalWerewolf** [comment]
mine says App library

**Comment by ElementalWerewolf** [comment]
can you also make it detect it even thought its not capitalized becasue it seams thats the problem with mine because its App library insted of App Library

**Comment by threethan** [comment]
I've replaced the app library apk with one that should detect these different strings. I'll push a proper update when the next major app update is ready, but for now you can go to shortcut settings, uninstall it, then manually re-install & re-enable it. Check if it works for you all.

**Comment by threethan** [comment]
Should be resolved in the latest [pre-release](https://github.com/threethan/LightningLauncher/releases/tag/7.0.0).
