### ISSUE TITLE
All my groups reset every time I open lightning launcher again

### ISSUE THREAD

**Issue by Flurmpy** [threethan/LightningLauncher#83]
When I set them and then open lightning launcher later all my groups reset

**Comment by threethan** [comment]
Could you provide a bit more detail on your issue, such as steps to replicate from a clean install?

Keep in mind that groups which do not contain any apps will be hidden by default.

**Comment by Flurmpy** [comment]
I downloaded it fresh from sidequest on the oculus quest 2 and every time I make a new group and add all the games to it, the next time I open the launcher they all reset. The groups are still there (usually), but the games are not in there

**Comment by threethan** [comment]
Please check if this is resolved in the latest [pre-release](https://github.com/threethan/LightningLauncher/releases/tag/7.0.0).

**Comment by Flurmpy** [comment]
That seemed to work, thanks!
