### ISSUE TITLE
The "Vader" series and "I Expect You to Die" series have the same icon

### ISSUE THREAD

**Issue by ZAKsPop** [threethan/LightningLauncher#84]
As the title says, these series of games show the same icon. So all 3 of my "Vader" games have the icon for Vader Immortal 3 and I Expect You to Die 2 has the icon for 3. I go in and update them and it corrects the issue but it doesn't stay. The problem reoccurs when I launch Lightning again. I even manually downloaded icons for them and used them but it doesn't last.

Latest version of Lightning Launcher on Quest 3 V60.

**Comment by threethan** [comment]
It seems like the launcher is for some reason ignoring numbers in the package names. The thing is, I'm not sure why, and this doesn't happen on my device with the same titles.

Could you try a fresh install of LightningLauncher as a sanity check?

It might somehow be Quest 3 specific issue, but I don't see why it would be. If anyone else can replicate this issue, please let me know what device you are on.

**Comment by threethan** [comment]
For reference, I expect you to die 1 is `com.schellgames.ieytdquest` while 2 is `com.schellgames.ieytd2` and 3 is `com.schellgames.ieytd3`.

Vader immortal games are: `com.ILMxLAB.VaderImmortal.ep1`,  `com.ILMxLAB.VaderImmortal.ep2`, &  `com.ILMxLAB.VaderImmortal.ep3`

**Comment by ZAKsPop** [comment]
Ugh. That didn't work and it totally hosed all of my settings. now I have to go back and fix all of the messed up names and icons.
![com oculus shellenv-20231230-075556](https://github.com/threethan/LightningLauncher/assets/62826396/d692ba7b-b182-4a9d-852a-74ee4deb1aea)

**Comment by threethan** [comment]
There's a settings backup option you could have used, sorry. It seems like Quest 3 might have issues with SharedPreferences. I've been looking to migrate to a better option, but I'm not sure if I can do so without a full reset for everyone.

**Comment by ZAKsPop** [comment]
Please do. This is annoying. Not that it prevents stuff from working, just nags at me.

**Comment by threethan** [comment]
Please check if this is resolved in the latest [pre-release](https://github.com/threethan/LightningLauncher/releases/tag/7.0.0).

**Comment by threethan** [comment]
Based on your other issue, I believe this to be fixed in version 7.0.0. If this is not the case, let me know so I can reopen it.
