### ISSUE TITLE
Cannot re-open minimized apps

### ISSUE THREAD

**Issue by SaifAqqad** [threethan/LightningLauncher#85]
Hey there, awesome work on this launcher, it's 100 times better than the stock one.

I have a small issue with the multitasking behavior when I open apps in their own windows and minimize them, as there's no way to reopen that window, especially the browser with background audio, there is a notification which I assume helps keep the browser running in the background but is it possible to add actions to that notification (to open the window, etc)?

**Comment by threethan** [comment]
I'm not sure if this would be possible due to how the Quest handles activities. Would it be preferable if you could resume apps which were not in their own windows?

**Comment by SaifAqqad** [comment]
sure, I just need a way to re-open the same instance of an app that was previously open (ex: discord app so i can mute or exit a call, yt music pwa so i can skip tracks or pause), not sure if this would be possible though.

**Comment by threethan** [comment]
You can reopen the same instance of the browser by just opening that same website again while it's running. Some native apps will provide their own notifications which allow for media control but not websites. I'll see what I can do, but this is mostly an OS limitation.

**Comment by threethan** [comment]
This is resolved in the latest [pre-release](https://github.com/threethan/LightningLauncher/releases/tag/7.0.0)!

**Comment by SaifAqqad** [comment]
I just tried the preview and it works perfectly, thank you so much.

![com oculus shellenv-20240106-082217](https://github.com/threethan/LightningLauncher/assets/47293197/351a7803-2ccc-4544-8feb-c3b6ff71bbe4)
