### ISSUE TITLE
Feature Request - Configure Guardian when Launching Apps

### ISSUE THREAD

**Issue by keld107** [threethan/LightningLauncher#86]
Hello! thank you so much for making this launcher!

im not sure if this is the right place to ask for this, because this is a feature request, but is it possible to have a button to disable the guardian boundary from the lightning launcher? and if so could it be possible to disable the boundary per app. so if i launch a mixed reality app from the launcher, the boundary turns off and then turns back on when the app closes?

sorry if this is not the place to ask, but i am willing to pay for this feature/ your work. 

thank you!

**Comment by threethan** [comment]
Totally fine to make a feature request, but I'm not currently aware of any way for third-party apps to modify guardian configuration. If one is found, this would be great to add, for now it's not planned.

**Comment by keld107** [comment]
questgamesoptimizer lets you disable the guardian boundary from the app :)

**Comment by threethan** [comment]
> questgamesoptimizer lets you disable the guardian boundary from the app :)

It seems to use ADB over wifi, acting as if it is a connected PC - which is a very clever trick, but outside the scope of this app.
