### ISSUE TITLE
Cannot scroll down the app list

### ISSUE THREAD

**Issue by GoodWillN1** [threethan/LightningLauncher#88]
The issue with scrolling jumping back to the top of the screen re-appeared in the latest Meta OS.
I cannot scroll down the app list. It jumps back up after like a second.

Launcher 6.3.0
Meta Quest 1
Version 50.0.0.198.257.455910822 (no Meta update available)

**Comment by threethan** [comment]
This issue should be resolved in the latest [pre-release](https://github.com/threethan/LightningLauncher/releases/tag/7.0.0).
