### ISSUE TITLE
Display as banner setting does not correctly apply

### ISSUE THREAD

**Issue by ZAKsPop** [threethan/LightningLauncher#90]
I've downloaded the version 7 preview. I was hoping that it would resolve the issue with the same icon being used on different versions of a game series. Unfortunately I can't tell because I can't get the VR Apps to not display as banners.
![com oculus shellenv-20240105-200024](https://github.com/threethan/LightningLauncher/assets/62826396/c70c3909-87ad-406d-adbb-03c99a14b7d0)

**Comment by threethan** [comment]
Try the new build on the updated prerelease. This was due to a rather silly oversight.
