### ISSUE TITLE
Feature Request: add the ability to toggle bottom quest 2 dock on and of when using 2d app so it does any them and have the toggle option so you can still move around the postion of window

### ISSUE THREAD

**Issue by Pickymarker** [threethan/LightningLauncher#98]
Feature Request: add the ability to toggle bottom quest 2 dock on and off when using 2d app so it does not get in the way or be annoying and have the toggle option so you can still move around the postion of window

**Comment by threethan** [comment]
As far as I am aware, this is not possible.
